{
 "title": "Red0ne Session Rollover investigations",
 "time": { "from": "2025-08-13T00:14:36.000Z", "to": "now" },
 "panels": [
  {
   "title": "Shannon Fallback Usage (%) by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(service_id) (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\", used_fallback=\"true\"}[$__rate_interval])) * 100) / sum by(service_id) (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p98 Latency Per Service (ms) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])) by (le, envoy_cluster_name, cluster)),\n  \"service_id\", \"$1\", \"envoy_cluster_name\", \".*middleware/([^/]+)-subdomain.*\"\n)",
     "legendFormat": "{{service_id}}_______{{cluster}}"
    }
   ]
  },
  {
   "title": "RelayMiner Relay Processing Durations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(relayminer_relay_duration_seconds_bucket{namespace=\"mainnet\"}[1m])))",
     "legendFormat": "relay_duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(relayminer_full_node_grpc_call_duration_seconds_bucket{namespace=\"mainnet\"}[1m])))",
     "legendFormat": "grpc_call_duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(relayminer_relay_request_preparation_duration_seconds_bucket{namespace=\"mainnet\"}[1m])))",
     "legendFormat": "request_preparation_seconds"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(relayminer_relay_response_preparation_duration_seconds_bucket{namespace=\"mainnet\"}[1m])))",
     "legendFormat": "response_preparation_seconds"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(relayminer_service_duration_seconds_bucket{namespace=\"mainnet\"}[1m])))",
     "legendFormat": "service_duration"
    }
   ]
  }
 ]
}