{
 "title": "WIP Path Traffic shifting dashboard",
 "time": { "from": "2025-04-09T23:48:42.381Z", "to": "2025-04-09T23:53:00.308Z" },
 "panels": [
  {
   "title": "morse errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(sanction_type, error_type) (rate(path_morse_relay_errors_total{cluster_name=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Morse requests by service id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service_id) (rate(path_morse_relays_total{cluster=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM requests total by EVM chainId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(chain_id) (rate(path_evm_requests_total{cluster=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM requests total by EVM chainId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(path_evm_requests_total{cluster=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Path morse relays total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(path_morse_relays_total{cluster=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(chain_id, error_type) (rate(path_evm_requests_total{cluster=\"portal-prd-asia-southeast1\", error_type!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}