{
 "title": "Envoy Clusters",
 "description": "Envoy proxy monitoring Dashboard with cluster and service level templates. ",
 "tags": [ "Data Plane" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live{})" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_allocated{})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$cluster\"})  - sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$cluster\"})-sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$cluster\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\"}) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} - in"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} - out"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"http.*\"}[5m]))",
     "legendFormat": "{{service}} - in"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"http.*\"}[5m]))",
     "legendFormat": "{{service}} - out"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\"}[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\"}[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\"}[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 50%"
    }
   ]
  },
  {
   "title": "Upstream 2xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"2\", envoy_cluster_name=~\"$cluster\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$cluster\",envoy_response_code_class=~\"4\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Downstream members",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$cluster\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$cluster\",service=~\"$service\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$cluster\",envoy_response_code_class=~\"5\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$cluster\",envoy_response_code_class=~\"3\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}