{
 "title": "Path Traffic",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "PATH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Path Morse Relays by Chain ID",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service_id) (rate(path_morse_relays_total{cluster=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Path Morse Success Rate by Chain",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(service_id) (path_morse_relays_total{ success=\"true\", namespace=\"middleware\", container=\"path\"}) * 100) / sum by(service_id) (path_morse_relays_total{namespace=\"middleware\", container=\"path\"})",
     "legendFormat": "{{request_method}}"
    }
   ]
  },
  {
   "title": "Path Morse Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(sanction_type, error_type) (rate(path_morse_relay_errors_total{cluster_name=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Path EVM Total Relays by EVM Chain ID",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(chain_id) (rate(path_evm_requests_total{cluster=\"portal-prd-asia-southeast1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Path EVM Success Rate by Method",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 14, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(chain_id, request_method) (path_evm_requests_total{ success=\"true\", namespace=\"middleware\", container=\"path\"}) * 100) / sum by(chain_id, request_method) (path_evm_requests_total{namespace=\"middleware\", container=\"path\"})",
     "legendFormat": "{{request_method}}"
    }
   ]
  },
  {
   "title": "Path EVM Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(chain_id, error_type) (rate(path_evm_requests_total{cluster=\"portal-prd-asia-southeast1\", error_type!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{container=\"path\", namespace=\"middleware\"}"
    }
   ]
  },
  {
   "title": "Portal Middleware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Middleware Mirrored Requests by `chain_alias`",
     "type": "timeseries",
     "description": "Shows the number of requests mirrored to PATH, categorized by chain alias",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum by(chain_alias) (count_over_time({cluster=\"$cluster\", container=\"middleware\"} |= `Successfully mirrored` | json | __error__=`` [$__interval]))"
      }
     ]
    },
    {
     "title": "Middleware log entries showing mirrored requests",
     "type": "logs",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", container=\"middleware\"} |= `Successfully mirrored`"
      }
     ]
    },
    {
     "title": "All logs (even if not mirrored) related to mirroring",
     "type": "logs",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", container=\"middleware\"} |= `mirror`"
      }
     ]
    },
    {
     "title": "EVM QoS logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", container=\"path\"} |= `EVM`"
      }
     ]
    }
   ]
  }
 ]
}