{
 "title": "Black Box Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "External Probes to Gateway",
   "type": "table",
   "description": "This Panel displays information about our external probes to the gateway endpoints.\n\nShould reflect actual status of front-facing users pinging the https://eth-mainnet.rpc.grove.city/v1/88f45de7 endpoint from multiple different regions.\n\nChain Used: Eth-Mainnet\n\nApplication ID: 88f45de7\n\nRequested Post-Data: '{\"method\": \"eth_blockNumber\",\"params\": [],\"id\": 1,\"jsonrpc\": \"2.0\"}'\n\nExpected data RegEX: '{\"jsonrpc\":\"2.0\",\"id\":(?P<id>\\d+),\"result\":\"0x(?P<result>[a-fA-F0-9]+)\"}'",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(probe_failed_due_to_regex{target=\"middleware-relay\"}) by (cluster)",
     "legendFormat": "probe_response_regex_match"
    },
    {
     "expr": "sum(probe_http_status_code{target=\"middleware-relay\"}) by (cluster)",
     "legendFormat": "probe_status_code"
    },
    {
     "expr": "sum(probe_duration_seconds{target=\"middleware-relay\"}) by (cluster)",
     "legendFormat": "probe_duration"
    },
    {
     "expr": "sum(probe_success{target=\"middleware-relay\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dispatcher Probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_status_code{service=\"prometheus-bb-exporter\", target=\"dispatcher-dispatch\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_success{service=\"prometheus-bb-exporter-portal-prd-us-west1-prometheus-blackbox\", target=\"dispatcher-height\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_success{service=\"prometheus-bb-exporter-portal-prd-us-west1-prometheus-blackbox\", target=\"dispatcher-dispatch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dispatch Probe duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{service=\"prometheus-bb-exporter-portal-prd-us-west1-prometheus-blackbox\", target=\"dispatcher-dispatch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "us-west1 Probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{service=\"prometheus-bb-exporter-portal-prd-us-west1-prometheus-blackbox\", target=\"middleware-health\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_success{service=\"prometheus-bb-exporter-portal-prd-us-west1-prometheus-blackbox\", target=\"r2-health\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_success{service=\"prometheus-bb-exporter-portal-prd-us-west1-prometheus-blackbox\", target=\"phd-health\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}