{
 "title": "[Dima fork] PATH stack",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# !!! DO NOT MAKE CHANGES !!!\n\nIf you need a panel from this dashboard - feel free to copy a panel to a different dashboard. If you need to change this dashboard, please duplicate this dashboard into your own first.\n\n## How to duplicate dashboard\n\n1. Click the settings on top tight of this dashboard\n2. Click \"save as\" on top right of this dashboard\n3. Change name (and directory, if desired)\n4. Click save.\n\n"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Relays by Region (path SYNTHETIC only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(path_requests_total{namespace=~\"middleware\", request_type!=\"REQUEST_TYPE_ORGANIC\", service=\"path-metrics\"}[$__interval]))",
     "legendFormat": "PATH - {{cluster}} (morse)"
    },
    {
     "expr": "sum by(cluster) (increase(path_requests_total{namespace=~\"middleware\", request_type!=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-beta-metrics|path-shannon-metrics\"}[$__interval]))",
     "legendFormat": "PATH - {{cluster}} (shannon-beta)"
    },
    {
     "expr": "sum by(cluster) (increase(path_requests_total{namespace=~\"middleware\", request_type!=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[$__interval]))",
     "legendFormat": "PATH - {{cluster}} (mainnet)"
    }
   ]
  },
  {
   "title": "Relays by Region (path ORGANIC only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-beta-metrics|path-shannon-metrics\"}[$__interval]))",
     "legendFormat": "PATH - {{cluster}} (shannon-beta)"
    },
    {
     "expr": "sum by(cluster) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[$__interval]))",
     "legendFormat": "PATH - {{cluster}} (mainnet)"
    }
   ]
  },
  {
   "title": "% of traffic goes to mainnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(\n  sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[1m]))\n  /\n  (\n    sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-beta-metrics|path-shannon-metrics\"}[1m]))\n    +\n    sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[1m]))\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relays by Region (path ORGANIC only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster,service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-beta-metrics|path-shannon-metrics\"}[$__interval]))",
     "legendFormat": "{{ service_id }} {{cluster}} (shannon-beta)"
    },
    {
     "expr": "sum by(cluster,service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[$__interval]))",
     "legendFormat": "{{ service_id }} {{cluster}} (mainnet)"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "PATH CPU us-east4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster_name=\"portal-prd-us-east4\", namespace=\"middleware\", image!=\"\", container=~\"path|path-shannon.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH CPU europe-west3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster_name=\"portal-prd-europe-west3\", namespace=\"middleware\", image!=\"\", container=~\"path|path-shannon.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH CPU asia-southeast1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster_name=\"portal-prd-asia-southeast1\", namespace=\"middleware\", image!=\"\", container=~\"path|path-shannon.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH RAM us-east4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_name=\"portal-prd-us-east4\", namespace=\"middleware\", image!=\"\", container=~\"path|path-shannon.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH RAM europe-west3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_name=\"portal-prd-europe-west3\", namespace=\"middleware\", image!=\"\", container=~\"path|path-shannon.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH RAM asia-southeast1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_name=\"portal-prd-asia-southeast1\", namespace=\"middleware\", image!=\"\", container=~\"path|path-shannon.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "goroutines us-east-4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"middleware\", container=~\".*path.*\", cluster=\"portal-prd-us-east4\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "goroutines eu-west3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"middleware\", container=~\".*path.*\", cluster=\"portal-prd-europe-west3\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "goroutines asia-southeast1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"middleware\", container=~\".*path.*\", cluster=\"portal-prd-asia-southeast1\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Auth Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(envoy_http_ext_authz_ok[5m])) / (sum(rate(envoy_http_ext_authz_ok[5m])) + sum(rate(envoy_http_ext_authz_denied[5m])))  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH Overall Health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 - (\n    sum(increase(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]) + \n        increase(envoy_cluster_upstream_cx_connect_fail{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]) + \n        increase(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]))\n    /\n    sum(increase(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]))\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Auth Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\".*auth.*\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency of PATH ressponses (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External Auth Service Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\".*auth.*\"}) / sum(envoy_cluster_membership_total{envoy_cluster_name=~\".*auth.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests by Chain/Service ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(chain_id) (\n  label_replace(\n    rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\"httproute/middleware/healthz.*\"}[$__rate_interval]),\n    \"chain_id\", \n    \"$1\", \n    \"envoy_cluster_name\", \n    \"httproute/middleware/([^.]+)-subdomain.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Services/Chains by Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  sum by(chain_id) (\n    label_replace(\n      increase(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\"}[$__range]),\n      \"chain_id\", \n      \"$1\", \n      \"envoy_cluster_name\", \n      \"httproute/middleware/([^-]+).*\"\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Service Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  histogram_quantile(0.9, \n    sum by(chain_id, le) (\n      label_replace(\n        rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\"}[$__rate_interval]),\n        \"chain_id\", \n        \"$1\", \n        \"envoy_cluster_name\", \n        \"httproute/middleware/([^-]+).*\"\n      )\n    )\n  )\n)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Top Chains by Non-2XX Responses: Total Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  sum by(chain_id) (\n    label_replace(\n      sum by(envoy_cluster_name) (\n        increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_response_code!~\"2..\"}[$__range])\n      ),\n      \"chain_id\", \n      \"$1\", \n      \"envoy_cluster_name\", \n      \"httproute/middleware/([^-]+).*\"\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Chains by Non-2XX Response Rate (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Percentage of non-2xx responses out of total requests for each chain\ntopk(10,\n  (\n    sum by(chain_id) (\n      label_replace(\n        sum by(envoy_cluster_name) (\n          increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_response_code!~\"2..\"}[$__range])\n        ),\n        \"chain_id\", \n        \"$1\", \n        \"envoy_cluster_name\", \n        \"httproute/middleware/([^-]+).*\"\n      )\n    )\n    /\n    sum by(chain_id) (\n      label_replace(\n        sum by(envoy_cluster_name) (\n          increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\"}[$__range])\n        ),\n        \"chain_id\", \n        \"$1\", \n        \"envoy_cluster_name\", \n        \"httproute/middleware/([^-]+).*\"\n      )\n    )\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Chains by Auth Failures (5m)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (chain) (\n    label_replace(\n      increase(envoy_http_ext_authz_denied{envoy_cluster_name=~\"securitypolicy/middleware/.*\"}[5m]),\n      \"chain\",\n      \"$1\",\n      \"envoy_cluster_name\",\n      \"securitypolicy/middleware/[^-]+-?([a-z0-9-]+)-?.*\"\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "PATH Total Requests: Organic + Synthetic",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(path_requests_total{namespace=\"middleware\"}[$__rate_interval]))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Morse Requests Success Rate",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(increase(path_morse_relays_total{namespace=\"middleware\", success=\"true\"}[$__rate_interval]))\n  / sum(increase(path_morse_relays_total{namespace=\"middleware\"}[$__rate_interval]))\n  * 100\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Organic Requests by Chain/Service",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 14, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_id) (rate(path_requests_total{namespace=\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EVM Requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(path_evm_requests_total{namespace=\"middleware\"}[$__rate_interval]))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "EVM Requests Success Rate: Organic + Synthetic",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(increase(path_evm_requests_total{namespace=\"middleware\", success=\"true\"}[5m])) /\n  sum(increase(path_evm_requests_total{namespace=\"middleware\"}[5m])) \n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relays By Chain: Organic + Synthetic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_id) (rate(path_morse_relays_total{namespace=\"middleware\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EVM Success Rate by Chain/Service",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "100 * sum by(service_id) (rate(path_evm_requests_total{namespace=\"middleware\", success=\"true\"}[$__interval])) / sum by(service_id) (rate(path_evm_requests_total{namespace=\"middleware\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PATH Organic vs. Syntheic Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Organic / Synthetic in US",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-asia-southeast1\"}[$__interval])) by (request_type)",
       "legendFormat": "{{request_type}}"
      }
     ]
    },
    {
     "title": "Organic / Synthetic in APAC",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-us-east4\"}[$__interval])) by (request_type)",
       "legendFormat": "{{request_type}}"
      }
     ]
    },
    {
     "title": "Organic / Synthetic in Europe",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-europe-west3\"}[$__interval])) by (request_type)",
       "legendFormat": "{{request_type}}"
      }
     ]
    }
   ]
  }
 ]
}