{
 "title": "Grace period count logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "TargetServiceID", "label": "TargetServiceID" },
   {
    "name": "service_ids",
    "label": "Set of service IDs to target in Critical Services queries",
    "query": {
     "query": "label_values(path_shannon_relays_total,service_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Exective Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Success Rate (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum (\n    increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])\n  )\n  -\n  sum (\n    increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\", envoy_response_code=~\"5..\"}[$__range])\n  )\n)\n/\nsum (\n  increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])\n)",
     "legendFormat": "Overall Success Rate (%)"
    }
   ]
  },
  {
   "title": "RPS (Requests Per Second)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Success Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "100 * (\n  sum (\n    increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])\n  )\n  -\n  sum (\n    increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\", envoy_response_code=~\"5..\"}[$__range])\n  )\n)\n/\nsum (\n  increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])\n)",
     "legendFormat": "Overall Success Rate (%)"
    }
   ]
  },
  {
   "title": "RPS (Requests Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum (\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])\n)",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Success Rate per Service (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by(chain_id) (\n    label_replace(\n      increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range]),\n      \"chain_id\", \"$1\", \"envoy_cluster_name\", \"httproute/middleware/([^-]+).*\"\n    )\n  )\n  -\n  sum by(chain_id) (\n    label_replace(\n      increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\", envoy_response_code=~\"5..\"}[$__range]),\n      \"chain_id\", \"$1\", \"envoy_cluster_name\", \"httproute/middleware/([^-]+).*\"\n    )\n  )\n)\n/\nsum by(chain_id) (\n  label_replace(\n    increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range]),\n    \"chain_id\", \"$1\", \"envoy_cluster_name\", \"httproute/middleware/([^-]+).*\"\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Organic Requests per Service ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_id) (\n  label_replace(\n    sum by(envoy_cluster_name) (\n      increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])\n    ),\n    \"service_id\", \n    \"$1\", \n    \"envoy_cluster_name\", \n    \"httproute/middleware/([^-]+).*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency Per Service (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])) by (le, envoy_cluster_name)),\n  \"service_id\", \"$1\", \"envoy_cluster_name\", \".*middleware/([^-]+)-subdomain.*\"\n)",
     "legendFormat": "{{service_id}}"
    }
   ]
  },
  {
   "title": "Shannon + Morse Count by Error Type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(error_type) (increase(path_morse_relay_errors_total[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(error_type) (increase(path_shannon_relay_errors_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed path versions",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "path_version_info{namespace=\"middleware\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH Error Logs (MainNet only)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\"path-shannon-mainnet\"} |= `error`"
    }
   ]
  },
  {
   "title": "Beta to Main Migration (Traffic, Success %, Logs on selected services)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "% traffic on Main vs Beta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "(\n  sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[1m]))\n  /\n  (\n    sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-beta-metrics|path-shannon-metrics\"}[1m]))\n    +\n    sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[1m]))\n  )\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Protocol Success Rate by Services selected (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "(\n  sum by(service_id) (increase(path_shannon_relays_total{success=\"true\", service_id=~\"$service_ids\"}[$__rate_interval]))\n  / \n  sum by(service_id) (increase(path_shannon_relays_total{service_id=~\"$service_ids\"}[$__rate_interval]))\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PATH Logs on Services selected",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container=~\"path-shannon-beta|path-shannon-mainnet\"} | json | service_id=~\"${service_ids:pipe}\""
      }
     ]
    }
   ]
  },
  {
   "title": "Shannon Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shannon Overall Success Rate (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(increase(path_shannon_relays_total{container=\"path-shannon-mainnet\", success=\"true\"}[$__rate_interval])) / \nsum(increase(path_shannon_relays_total{container=\"path-shannon-mainnet\"}[$__rate_interval])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shannon Endpoint Payload Validation Errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 206 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container=\"path-shannon-mainnet\"} |= `Failed to validate`"
      }
     ]
    },
    {
     "title": "Shannon Total Requests (Organic + Synthetic)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 214 },
     "targets": [
      {
       "expr": "sum by() (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shannon Unhandled Endpoint Errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 214 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container=\"path-shannon-mainnet\"} |= `code update needed`"
      }
     ]
    },
    {
     "title": "Shannon Total Sanctions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(path_shannon_sanctions_by_domain{container=\"path-shannon-mainnet\"}[$__rate_interval]))",
       "legendFormat": "{{endpoint_domain}},{{sanction_reason}}"
      }
     ]
    },
    {
     "title": "Shannon Sanctions by Endpoint Domain and Service ID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(endpoint_domain, service_id) (increase(path_shannon_sanctions_by_domain{container=\"path-shannon-mainnet\"}[$__rate_interval]))",
       "legendFormat": "{{service_id}} - {{endpoint_domain}}"
      }
     ]
    },
    {
     "title": "Shannon Sanctions by Endpoint Domain and Error Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(endpoint_domain, sanction_reason) (increase(path_shannon_sanctions_by_domain{container=\"path-shannon-mainnet\"}[$__rate_interval]))",
       "legendFormat": "{{endpoint_domain}},{{sanction_reason}}"
      }
     ]
    },
    {
     "title": "Internal Errorrs by Service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_id, error_type) (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\", error_type!=\"\"}[$__rate_interval]))",
       "legendFormat": "{{service_id}} - {{error_type}}"
      }
     ]
    },
    {
     "title": "Shannon Overall Success Rate by Service (%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  sum by(service_id) (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\", success=\"true\"}[$__rate_interval])) * 100\n  or\n  (sum by(service_id) (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\"}[$__rate_interval])) * 0)\n) \n/ \nsum by(service_id) (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\"}[$__rate_interval]))",
       "legendFormat": "{{service_id}}"
      }
     ]
    },
    {
     "title": "Shannon Total Requests by Service (Organic + Synthetic)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_id) (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\"}[$__rate_interval]))",
       "legendFormat": "{{service_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sanctions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Sanctions by Service",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 950 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (service_id) (increase(path_shannon_sanctions_by_domain{container=\"path-shannon-beta\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Sanctions by Endpoint Domain",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 950 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (endpoint_domain) (increase(path_shannon_sanctions_by_domain{container=\"path-shannon-beta\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sanctions Breakdown by Service and Domain",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 985 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (service_id, endpoint_domain) (increase(path_shannon_sanctions_by_domain{container=\"path-shannon-beta\"}[$__range]))",
       "legendFormat": "{{service_id}} - {{endpoint_domain}}"
      }
     ]
    },
    {
     "title": "Sanctions Breakdown by Service and Reason",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 985 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (service_id, sanction_reason) (increase(path_shannon_sanctions_by_domain{container=\"path-shannon-beta\"}[$__range]))",
       "legendFormat": "{{service_id}} - {{sanction_reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth Success Rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 951 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * sum(rate(envoy_http_ext_authz_ok[5m])) / (sum(rate(envoy_http_ext_authz_ok[5m])) + sum(rate(envoy_http_ext_authz_denied[5m])))  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PATH Overall Health",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 951 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  1 - (\n    sum(increase(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]) + \n        increase(envoy_cluster_upstream_cx_connect_fail{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]) + \n        increase(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]))\n    /\n    sum(increase(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]))\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 951 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "95th Percentile Auth Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 951 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\".*auth.*\"}[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 Latency of PATH ressponses (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 951 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\"}[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "External Auth Service Availability",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 951 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\".*auth.*\"}) / sum(envoy_cluster_membership_total{envoy_cluster_name=~\".*auth.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests by Chain/Service ID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 959 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(chain_id) (\n  label_replace(\n    envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\"},\n    \"chain_id\", \n    \"$1\", \n    \"envoy_cluster_name\", \n    \"httproute/middleware/([^-]+).*\"\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top Services/Chains by Traffic",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 959 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, \n  sum by(chain_id) (\n    label_replace(\n      increase(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"httproute/middleware/.*\"}[$__range]),\n      \"chain_id\", \n      \"$1\", \n      \"envoy_cluster_name\", \n      \"httproute/middleware/([^-]+).*\"\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P90 Service Response Time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 959 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,\n  histogram_quantile(0.9, \n    sum by(chain_id, le) (\n      label_replace(\n        rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\"}[$__rate_interval]),\n        \"chain_id\", \n        \"$1\", \n        \"envoy_cluster_name\", \n        \"httproute/middleware/([^-]+).*\"\n      )\n    )\n  )\n)",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "Top Chains by Non-2XX Responses: Total Requests",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 967 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,\n  sum by(chain_id) (\n    label_replace(\n      sum by(envoy_cluster_name) (\n        increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_response_code!~\"2..\"}[$__range])\n      ),\n      \"chain_id\", \n      \"$1\", \n      \"envoy_cluster_name\", \n      \"httproute/middleware/([^-]+).*\"\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top Chains by Non-2XX Response Rate (%)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 967 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "# Percentage of non-2xx responses out of total requests for each chain\ntopk(10,\n  (\n    sum by(chain_id) (\n      label_replace(\n        sum by(envoy_cluster_name) (\n          increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_response_code!~\"2..\"}[$__range])\n        ),\n        \"chain_id\", \n        \"$1\", \n        \"envoy_cluster_name\", \n        \"httproute/middleware/([^-]+).*\"\n      )\n    )\n    /\n    sum by(chain_id) (\n      label_replace(\n        sum by(envoy_cluster_name) (\n          increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\"}[$__range])\n        ),\n        \"chain_id\", \n        \"$1\", \n        \"envoy_cluster_name\", \n        \"httproute/middleware/([^-]+).*\"\n      )\n    )\n  ) * 100\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PATH: full node utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pavers endpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 690 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "round(sum(irate(nginx_ingress_controller_requests{ingress=~\".*pavers.*\"}[2m])) by (ingress), 0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BETA pavers endpoint requests type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 690 },
     "targets": [
      {
       "expr": "kubernetes.pod_namespace:\"ingress-nginx\" AND \"testnet-beta-testnet-beta-pavers-grpc\" \n| extract \"<client_ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <body_bytes> \\\"<referrer>\\\" \\\"<user_agent>\\\" <upstream_time_ms> <request_time_s> [<upstream_group>] [] <upstream_addr> <upstream_bytes> <upstream_duration_s> <upstream_status> <request_id>\"\n| stats by(path) count() as hits\n| sort by(hits desc)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "PATH Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total - Traffic shifting",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(middleware_recorder_relays{container=\"middleware\", event=\"network_relay_recorded\"}[30s]))",
       "legendFormat": "middleware - {{cluster}}"
      },
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\"}[30s]))",
       "legendFormat": "PATH - {{cluster}} (morse)"
      }
     ]
    },
    {
     "title": "US - Traffic shifting",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(middleware_recorder_relays{container=\"middleware\", event=\"network_relay_recorded\", cluster=\"portal-prd-us-east4\"}[30s]))",
       "legendFormat": "middleware - {{cluster}}"
      },
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-us-east4\", request_type=\"REQUEST_TYPE_ORGANIC\"}[30s]))",
       "legendFormat": "PATH - {{cluster}} (morse)"
      }
     ]
    },
    {
     "title": "Europe - Traffic shifting",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(middleware_recorder_relays{container=\"middleware\", event=\"network_relay_recorded\", cluster=\"portal-prd-europe-west3\"}[30s]))",
       "legendFormat": "middleware - {{cluster}}"
      },
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-europe-west3\", request_type=\"REQUEST_TYPE_ORGANIC\"}[30s]))",
       "legendFormat": "PATH - {{cluster}} (morse)"
      }
     ]
    },
    {
     "title": "APAC - Traffic shifting",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(middleware_recorder_relays{container=\"middleware\", event=\"network_relay_recorded\", cluster=\"portal-prd-asia-southeast1\"}[30s]))",
       "legendFormat": "middleware - {{cluster}}"
      },
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-asia-southeast1\", request_type=\"REQUEST_TYPE_ORGANIC\"}[30s]))",
       "legendFormat": "PATH - {{cluster}} (morse)"
      }
     ]
    },
    {
     "title": "Total relays (Organic + Synthetic) over the last 24 hours",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(path_morse_relays_total{}[24h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Fluentd Written Records",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(fluentd_output_status_emit_records{type=\"bigquery_insert\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relays by Region (middleware vs path)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1140 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(cluster) (increase(middleware_recorder_relays{container=\"middleware\", event=\"network_relay_recorded\"}[$__interval]))",
       "legendFormat": "middleware - {{cluster}}"
      },
      {
       "expr": "sum by(cluster) (increase(path_morse_relays_total{namespace=~\"middleware\"}[$__interval]))",
       "legendFormat": "PATH - {{cluster}} (morse)"
      }
     ]
    },
    {
     "title": "Relays by Region (path ORGANIC only)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1140 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(cluster) (increase(middleware_recorder_relays{container=\"middleware\", event=\"network_relay_recorded\"}[$__interval]))",
       "legendFormat": "middleware - {{cluster}}"
      },
      {
       "expr": "sum by(cluster) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\"}[$__interval]))",
       "legendFormat": "PATH - {{cluster}} (morse)"
      }
     ]
    },
    {
     "title": "Morse Requests Success Rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1148 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(increase(path_morse_relays_total{namespace=\"middleware\", success=\"true\"}[$__rate_interval]))\n  / sum(increase(path_morse_relays_total{namespace=\"middleware\"}[$__rate_interval]))\n  * 100\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PATH Total Requests: Organic + Synthetic",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(path_requests_total{namespace=\"middleware\"}[$__rate_interval]))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Morse Success Rate by Service ID (%)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1148 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  sum by (service_id) (increase(path_morse_relays_total{namespace=\"middleware\", success=\"true\"}[$__rate_interval]))\n  / sum by (service_id) (increase(path_morse_relays_total{namespace=\"middleware\"}[$__rate_interval]))\n  * 100\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Morse Protocol Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1148 },
     "targets": [
      {
       "expr": "{container=\"path\"} |= `morse` |= `relay error occurred`"
      }
     ]
    },
    {
     "title": "EVM ORGANIC Requests Success Rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1156 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  sum(increase(path_evm_requests_total{namespace=\"middleware\", service=\"path-metrics\", success=\"true\", request_origin=\"REQUEST_ORIGIN_ORGANIC\"}[$__rate_interval])) /\n  sum(increase(path_evm_requests_total{namespace=\"middleware\", service=\"path-metrics\", request_origin=\"REQUEST_ORIGIN_ORGANIC\"}[$__rate_interval])) \n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EVM Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(path_evm_requests_total{namespace=\"middleware\"}[$__rate_interval]))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "EVM ORGANIC Requests Success Rate by Service",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1156 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  sum by (service_id) (\n    label_replace(\n      increase(path_evm_requests_total{namespace=\"middleware\",service=\"path-metrics\", request_origin=\"REQUEST_ORIGIN_ORGANIC\", success=\"true\"}[$__interval]),\n      \"service_id\", \"Unspecified\", \"service_id\", \"^$\"\n    )\n  ) /\n  sum by (service_id) (\n    label_replace(\n      increase(path_evm_requests_total{namespace=\"middleware\", service=\"path-metrics\", request_origin=\"REQUEST_ORIGIN_ORGANIC\",}[$__interval]),\n      \"service_id\", \"Unspecified\", \"service_id\", \"^$\"\n    )\n  )\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QoS EVM Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1156 },
     "targets": [
      {
       "expr": "{container=\"path\"} |~ `(?i)evm`"
      }
     ]
    },
    {
     "title": "Total Organic Requests by Chain/Service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_id) (rate(path_requests_total{namespace=\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Morse Request Success Rate by Service (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1164 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sort(\n  (\n    sum by (service_id) (increase(path_morse_relays_total{namespace=\"middleware\", success=\"true\"}[$__rate_interval]))\n    / sum by (service_id) (increase(path_morse_relays_total{namespace=\"middleware\"}[$__rate_interval]))\n    * 100\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Morse Rate of Endpoint Errors by Error Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(error_type) (rate(path_morse_relay_errors_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EVM Failed Organic Requests Error Type by Service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1172 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(error_type, service_id) (rate(path_evm_requests_total{success=\"false\", request_origin=\"REQUEST_ORIGIN_ORGANIC\"}[$__rate_interval]))",
       "legendFormat": "{{service_id}},{{error_type}}"
      }
     ]
    },
    {
     "title": "EVM Success Rate by Service (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1172 },
     "targets": [
      {
       "expr": "100 * sum by(service_id) (rate(path_evm_requests_total{namespace=\"middleware\", success=\"true\"}[$__interval])) / sum by(service_id) (rate(path_evm_requests_total{namespace=\"middleware\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shannon (Beta Testnet) Fetch Session Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1180 },
     "targets": [
      {
       "expr": "{container=\"path-shannon-beta\"} |= `error getting a session`"
      }
     ]
    }
   ]
  },
  {
   "title": "Non-2xx Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true
  },
  {
   "title": "PATH Organic vs. Syntheic Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Organic / Synthetic in US",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1967 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-asia-southeast1\"}[$__interval])) by (request_type)",
       "legendFormat": "{{request_type}}"
      }
     ]
    },
    {
     "title": "Organic / Synthetic in APAC",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1967 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-us-east4\"}[$__interval])) by (request_type)",
       "legendFormat": "{{request_type}}"
      }
     ]
    },
    {
     "title": "Organic / Synthetic in Europe",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1967 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum  (increase(path_requests_total{namespace=~\"middleware\", cluster=\"portal-prd-europe-west3\"}[$__interval])) by (request_type)",
       "legendFormat": "{{request_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PATH Overview by Region: $Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "repeat": "Cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "PATH Total Requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1988 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(path_requests_total{namespace=\"middleware\", cluster=\"$Cluster\"}[$__rate_interval]))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Morse Requests Success Rate",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1988 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(increase(path_morse_relays_total{namespace=\"middleware\",cluster=\"$Cluster\", success=\"true\"}[$__rate_interval]))\n  / sum(increase(path_morse_relays_total{namespace=\"middleware\", cluster=\"$Cluster\"}[$__rate_interval]))\n  * 100\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Organic Requests by Chain/Service",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 14, "y": 1988 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_id) (rate(path_requests_total{namespace=\"middleware\",cluster=\"$Cluster\", request_type=\"REQUEST_TYPE_ORGANIC\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EVM Requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1995 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(path_evm_requests_total{namespace=\"middleware\", cluster=\"$Cluster\"}[$__rate_interval]))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "EVM Requests Success Rate: Organic + Synthetic",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1995 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(increase(path_evm_requests_total{namespace=\"middleware\",cluster=\"$Cluster\", success=\"true\"}[$__rate_interval])) /\n  sum(increase(path_evm_requests_total{namespace=\"middleware\", cluster=\"$Cluster\"}[$__rate_interval])) \n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relays By Chain: Organic + Synthetic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 2002 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_id) (rate(path_morse_relays_total{namespace=\"middleware\", cluster=\"$Cluster\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EVM Success Rate by Chain/Service",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 2002 },
     "targets": [
      {
       "expr": "100 * sum by(service_id) (rate(path_evm_requests_total{namespace=\"middleware\",cluster=\"$Cluster\", success=\"true\"}[$__interval])) / sum by(service_id) (rate(path_evm_requests_total{namespace=\"middleware\", cluster=\"$Cluster\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Session Rollover Investigation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Latency Per Service/Region (poly, eth, xrpl)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/(poly|xrplevm-testnet|eth)-.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])) by (le, envoy_cluster_name, cluster)),\n    \"service\", \"$1\", \"envoy_cluster_name\", \"httproute/middleware/(.+)-[^-]+$\"\n  ),\n  \"region\", \"$1\", \"cluster\", \"portal-prd-(.*)\"\n)",
     "legendFormat": "{{service}}-{{region}}"
    }
   ]
  },
  {
   "title": "Latency Per Region (all services)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__rate_interval])) by (le, cluster)),\n  \"region\", \"$1\", \"cluster\", \"portal-prd-(.*)\"\n)",
     "legendFormat": "{{service}}-{{region}}"
    }
   ]
  },
  {
   "title": "Grace Period Logs",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "direction": "backward",
     "expr": "label_replace(\n  count_over_time({container=~\"path-shannon-mainnet\"} |= \"grace period\" |= \"IS NOT WITHIN\"[5m]),\n  \"status\", \"NOT Within Grace Period\", \"\", \"\"\n)",
     "legendFormat": "NOT Within Grace Period"
    },
    {
     "direction": "backward",
     "expr": "label_replace(\n  count_over_time({container=~\"path-shannon-mainnet\"} |= \"grace period\" |= \"IS WITHIN\"[5m]),\n  \"status\", \"Within Grace Period\", \"\", \"\"\n)",
     "legendFormat": "Within Grace Period"
    }
   ]
  }
 ]
}