{
 "title": "[Dima] path troubleshooting",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(path_evm_requests_total,cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(path_evm_requests_total{cluster_name=\"$cluster\"},pod)"
    }
   },
   {
    "name": "TargetServiceID",
    "label": "The Service ID under investigation."
   }
  ]
 },
 "panels": [
  {
   "title": "Callout",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "# !!! DO NOT MAKE CHANGES !!!\n\nIf you need a panel from this dashboard - feel free to copy a panel to a different dashboard. If you need to change this dashboard, please duplicate this dashboard into your own.\n\n## How to duplicate dashboard\n\n1. Click the settings on top tight of this dashboard\n2. Click \"save as\" on top right of this dashboard\n3. Change name (and directory, if desired)\n4. Click save.\n\n"
   }
  },
  { "title": "EVM metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "EVM requests by chain ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(path_evm_requests_total{pod=~\"$pod\"}[$__interval])) by (chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(path_evm_requests_total{pod=~\"$pod\", error_type!=\"\"}[$__interval])) by (error_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succsefull EVM requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(path_evm_requests_total{pod=~\"$pod\", error_type=\"\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PATH requests data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PATH requests total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (increase(path_requests_total{pod=~\"$pod\"}[$__interval])) by (request_type,request_error_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU usage / requests / limits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster_name=\"$cluster\", image!=\"\", pod=\"$pod\", container!=\"\"}[$__rate_interval])) by (container, pod)",
     "legendFormat": "{{pod}}, {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster\", pod=\"$pod\", unit=\"core\"}) by (container, pod)",
     "legendFormat": "{{pod}}, {{container}} limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", pod=\"$pod\", unit=\"core\"}) by (container, pod)",
     "legendFormat": "{{pod}}, {{container}} requests"
    }
   ]
  },
  {
   "title": "Memory usage / requests / limits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_name=\"$cluster\", image!=\"\", pod=\"$pod\", container!=\"\"}) by (container, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster\", pod=\"$pod\", container!=\"\", resource=\"memory\"}) by (container, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", pod=\"$pod\", container!=\"\", resource=\"memory\"}) by (container, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Pod logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{namespace=\"middleware\", pod=~\"$pod\"} |= ``"
    }
   ]
  },
  {
   "title": "Non-2xx Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Protocol-level errors (Morse) for Service ID",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", container=\"path\"} |= `relay error occurred` | json | service_id = `$TargetServiceID`"
      }
     ]
    }
   ]
  }
 ]
}