{
 "title": "PATH Service Dashboard",
 "tags": [
  "path",
  "pocket-network",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(path_requests_total, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(path_requests_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(path_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(path_requests_total,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Current state of PATH service including request volume, error rates, and system resource utilization.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(path_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM Error Rate",
   "type": "stat",
   "description": "Percentage of EVM requests that resulted in an error",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(increase(path_evm_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", success=\"false\", service=~\"$service\"}[$__rate_interval])) by (cluster) / sum(increase(path_evm_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "Error % {{ cluster }}"
    }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "stat",
   "description": "Current number of active goroutines",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{pod}} ({{cluster}})"
    }
   ]
  },
  { "title": "Request & Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "% of traffic routed to mainnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(\n  sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[1m]))\n  /\n  (\n    sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-beta-metrics|path-shannon-metrics\"}[1m]))\n    +\n    sum by(service_id) (increase(path_requests_total{namespace=~\"middleware\", request_type=\"REQUEST_TYPE_ORGANIC\", service=~\"path-shannon-mainnet-metrics\"}[1m]))\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "Distribution of request processing times",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(path_relay_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(path_relay_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(path_relay_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Rate of requests processed by the PATH service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(request_type) (rate(path_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "EVM Response Status Codes",
   "type": "timeseries",
   "description": "HTTP status codes returned by the PATH service for EVM requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(path_evm_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "EVM Requests by Method",
   "type": "timeseries",
   "description": "Rate of EVM requests by method type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(request_method) (rate(path_evm_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{request_method}}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of PATH service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Current ({{pod}})"
    },
    {
     "expr": "go_memstats_sys_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "System ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of PATH service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "description": "File descriptors in use by the PATH service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Open FDs ({{pod}})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network traffic to and from the PATH service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "Received ({{pod}})"
    },
    {
     "expr": "rate(process_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "Transmitted ({{pod}})"
    }
   ]
  }
 ]
}