{
 "title": "Fluentd dashboard (Prometheus exporter)",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Output status emit records",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_records{type=~\"bigquery.*\"}[$__rate_interval])) by (cluster_name, type)"
    }
   ]
  },
  {
   "title": "buffer queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(fluentd_status_buffer_queue_length{type=~\"bigquery.*\"}[$__interval]) by (cluster_name, type)"
    }
   ]
  },
  {
   "title": "buffer total queued size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "  sum(fluentd_status_buffer_total_bytes{type=~\"bigquery.*\"}[$__interval]) by (cluster_name, type)"
    }
   ]
  },
  {
   "title": "retry count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(fluentd_status_retry_count{type=~\"bigquery.*\"}[$__interval])) by (cluster_name, type)"
    }
   ]
  }
 ]
}