{
 "title": "RelayMiners - Suppliers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(relayminer_requests_total,namespace)"
    }
   },
   {
    "name": "supplier_operator_address",
    "query": {
     "query": "label_values(relayminer_requests_total{namespace=\"$namespace\"},supplier_operator_address)"
    }
   },
   {
    "name": "service_id",
    "query": {
     "query": "label_values(relayminer_requests_total{namespace=\"$namespace\"},service_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relayminer CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\", container=~\"relayminer\"}[$__rate_interval])) by (pod)"
      }
     ]
    },
    {
     "title": "PATH RAM us-east4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", container=~\"relayminer\"}) by (pod)"
      }
     ]
    }
   ]
  },
  { "title": "Request metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(relayminer_requests_total{namespace=\"$namespace\", supplier_operator_address=~\"$supplier_operator_address\", service_id=~\"$service_id\"}[1m])) by (supplier_operator_address, service_id)",
     "legendFormat": "{{service_id}}-{{supplier_operator_address}}"
    }
   ]
  },
  {
   "title": "Stake",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "cosmos_wallets_exporter_supplier_stake{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal E2E Relay Latency",
   "type": "heatmap",
   "description": "The latency that includes the RM's internal overhead AND the latency of the backend service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(relayminer_relay_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External E2E Relay Latency (nginx POV)",
   "type": "heatmap",
   "description": "The E2E Relay latency from nginx's POV",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",exported_namespace=~\"$namespace\",exported_service=~\".*relayminer.*\"}[2m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full Node (RPC) latency (mainnet only)",
   "type": "heatmap",
   "description": "RM to FullNode RPC latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"mainnet-fullnodes-rpc-relayminers-internal\"}[2m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full Node (gRPC) latency (mainnet only)",
   "type": "heatmap",
   "description": "RM to FullNode gRPC latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"mainnet-fullnodes-grpc-relayminers-internal\"}[2m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume by Domain - ${service_id} Mainnet",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(path_shannon_endpoint_latency_seconds_count{service_id=~\"$service_id\", container=\"path-shannon-mainnet\"}[$__interval])) by (endpoint_domain)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RelayMiner Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RelayMiners Error Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:\"$namespace\" AND kubernetes.container_name: \"relayminer\" AND log.level: \"error\"\n"
    }
   ]
  },
  {
   "title": "RelayMiners Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:\"$namespace\" AND kubernetes.container_name: \"relayminer\""
    }
   ]
  }
 ]
}