{
 "title": "Spamming relays - client PoV",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Endpoint latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:\"mainnet\" AND kubernetes.container_name:\"requests-spammer\" AND log.duration_ms:*\n| stats by (log.endpoint) avg(log.duration_ms) as avg_duration_ms\n| sort by (avg_duration_ms) desc",
     "legendFormat": "{{log.endpoint}}"
    }
   ]
  },
  {
   "title": "esponse Time Percentiles by Endpoint (P50, P90, P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:\"mainnet\" AND kubernetes.container_name:\"requests-spammer\" AND log.duration_ms:*\n| stats by (log.endpoint) \n  quantile(0.5, log.duration_ms) p50_ms,\n  quantile(0.9, log.duration_ms) p90_ms,\n  quantile(0.99, log.duration_ms) p99_ms"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:\"mainnet\" AND kubernetes.container_name:\"requests-spammer\" AND log.error:*"
    }
   ]
  }
 ]
}