{
 "title": "Executive Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "** DISCLAIMER **",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 🚨 THIS DASHBOARD COSTS MONEY! 🚨 \n💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸\n\n## ⚠️⚠️⚠️ **Every time you refresh this dashboard, it runs VERY EXPENSIVE queries on BigQuery** ⚠️⚠️⚠️\n\n💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸💸\n### DO NOT set the TIME RANGE to values larger than 24 hours unless it's worth the 💰. Bias to just a few hours."
   }
  },
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Service Uptime",
   "type": "stat",
   "description": "Source: Envoy Gateway\n\nDefinition: The % of non-5xx at the Envoy Gateway Level. \n\n** Success rate is governed by Uptime. **",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum (\n    increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\", envoy_response_code!~\"[5]..\"}[$__range])\n  )\n)\n/\nsum (\n  increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Requests Per Second (RPS)",
   "type": "stat",
   "description": "Source: Envoy\n\nDefinition: Average RPS of the Gateway.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency [P95] (ms)",
   "type": "stat",
   "description": "Source: Envoy\n\nDefinition: The average 95th percentile latency calculated by Envoy Gateway.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/middleware/.*\", envoy_cluster_name!~\".*healthz.*\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATH Relays",
   "type": "stat",
   "description": "Source: PATH (VictoriaMetrics)\n\nDefinition: Total Relays counted in Victoria Metrics by PATH.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(path_shannon_relays_total{container=\"path-shannon-mainnet\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DWH Relays",
   "type": "stat",
   "description": "Source: DWH\n\nDefinition: Total Relays Captured in DWH.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "SELECT \n  count(*)\nFROM `portal-prd-gke-all.RELAYS.D2` r\nWHERE \n  r.date BETWEEN DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__from:date:seconds}), DAY)) AND DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__to:date:seconds}), DAY))\n  AND r.ts BETWEEN TIMESTAMP_SECONDS(${__from:date:seconds}) AND TIMESTAMP_SECONDS(${__to:date:seconds})\n;"
    }
   ]
  },
  {
   "title": "Service Uptime - 30s rolling avg",
   "type": "timeseries",
   "description": "Source: Envoy\n\nDefinition: The % of non-5xx at the Envoy Gateway Level. \n\n** Success rate cannot exceed Uptime. **",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(envoy_cluster_upstream_rq{\n    envoy_cluster_name=~\"httproute/middleware/.*\",\n    envoy_cluster_name!~\".*healthz.*\",\n    envoy_response_code!~\"[5]..\"\n  }[30s])\n)\n/\nclamp_min(\n  sum(\n    rate(envoy_cluster_upstream_rq{\n      envoy_cluster_name=~\"httproute/middleware/.*\",\n      envoy_cluster_name!~\".*healthz.*\"\n    }[30s])\n  ),\n  1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS) - 30s rolling avg",
   "type": "timeseries",
   "description": "Source: Envoy",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(envoy_cluster_upstream_rq{\n    envoy_cluster_name=~\"httproute/middleware/.*\",\n    envoy_cluster_name!~\".*healthz.*\"\n  }[30s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "description": "Source: Envoy",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le)(\n    rate(envoy_cluster_upstream_rq_time_bucket{\n      envoy_cluster_name=~\"httproute/middleware/.*\",\n      envoy_cluster_name!~\".*healthz.*\"\n    }[30s])\n  )\n)",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(envoy_cluster_upstream_rq_time_bucket{\n      envoy_cluster_name=~\"httproute/middleware/.*\",\n      envoy_cluster_name!~\".*healthz.*\"\n    }[30s])\n  )\n)",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "Success Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Overall Success Rate",
   "type": "stat",
   "description": "Source: DWH\n\nDefinition: Total Number of 5XX errors / Total Number of Requests \n\n** Removes 4XX from consideration **",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "SELECT\n  SAFE_DIVIDE(\n    COUNT(CASE WHEN is_error = FALSE OR error_type = 'user' OR error_type IS NULL THEN 1 END),\n    COUNT(*)\n  ) AS success_rate\nFROM `portal-prd-gke-all.RELAYS.D2` r\nWHERE\n  r.date BETWEEN DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__from:date:seconds}), DAY)) \n                  AND DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__to:date:seconds}), DAY))\n  AND r.ts BETWEEN TIMESTAMP_SECONDS(${__from:date:seconds}) \n                   AND TIMESTAMP_SECONDS(${__to:date:seconds})\n;\n"
    }
   ]
  },
  {
   "title": "Service Success Rates",
   "type": "timeseries",
   "description": "Source: DWH\n\nDefinition: Success Rate by Service summarized each minute\n\n** MUST HAVE >10 RPS **",
   "gridPos": { "h": 14, "w": 15, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(r.ts, MINUTE) AS time,\n  r.chain_id,\n  SAFE_DIVIDE(\n    COUNT(CASE WHEN is_error = FALSE OR error_type = 'user' OR error_type IS NULL THEN 1 END),\n    COUNT(*)\n  ) AS success_rate\nFROM `portal-prd-gke-all.RELAYS.D2` r\nWHERE\n  r.date BETWEEN DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__from:date:seconds}), DAY)) \n                  AND DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__to:date:seconds}), DAY))\n  AND r.ts BETWEEN TIMESTAMP_SECONDS(${__from:date:seconds}) \n                   AND TIMESTAMP_SECONDS(${__to:date:seconds})\n  AND r.chain_id <> ''\nGROUP BY \n  TIMESTAMP_TRUNC(r.ts, MINUTE),\n  r.chain_id\nHAVING\n  COUNT(*) >= 600\nORDER BY \n  time,\n  r.chain_id\n;"
    }
   ]
  },
  { "title": "Platform Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Paid Relay %",
   "type": "stat",
   "description": "Source: DWH\n\nDefinition: % of all requests that are Paid.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "SELECT\n  SAFE_DIVIDE(\n    COUNT(CASE WHEN a.plan_type IN ('PLAN_UNLIMITED', 'ENTERPRISE') THEN 1 END),\n    COUNT(*)\n  ) AS enterprise_relay_percentage\nFROM `portal-prd-gke-all.RELAYS.D2` r\nJOIN `portal-prd-gke-all.PORTAL.accounts` a ON r.portal_account_id = a.id\nWHERE\n  r.date BETWEEN DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__from:date:seconds}), DAY)) \n                  AND DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__to:date:seconds}), DAY))\n  AND r.ts BETWEEN TIMESTAMP_SECONDS(${__from:date:seconds}) \n                   AND TIMESTAMP_SECONDS(${__to:date:seconds})\n  AND a.id IS NOT NULL\n  AND r.portal_account_id <> '47eadadd'\n;"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "stat",
   "description": "Source: DWH\n\nDefinition: Unique Accounts with relay activity.",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "SELECT\n  count( distinct(portal_account_id)),\nFROM `portal-prd-gke-all.RELAYS.D2` r\nWHERE\n  r.date BETWEEN DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__from:date:seconds}), DAY)) \n                  AND DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__to:date:seconds}), DAY))\n  AND r.ts BETWEEN TIMESTAMP_SECONDS(${__from:date:seconds}) \n                   AND TIMESTAMP_SECONDS(${__to:date:seconds})\n;"
    }
   ]
  },
  {
   "title": "Estimated Revenue (Month to Date)",
   "type": "stat",
   "description": "Source: DWH\n\nDefinition: Estimated Revenue MTD.\n\n** DOES NOT RESPECT TIME SELECTORS **",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "SELECT\n  (5 * count(*) / 1000000) as est_revenue,\nFROM `portal-prd-gke-all.RELAYS.D2` r\nJOIN `portal-prd-gke-all.PORTAL.accounts` a on a.id = r.portal_account_id\nWHERE\n  r.date BETWEEN DATE_TRUNC(CURRENT_DATE(), MONTH) AND DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 1 MONTH)\n  AND a.plan_type = 'PLAN_UNLIMITED'\n  --remove GROVE INFRA, Radix, Kaia, Polygon\n  AND r.portal_account_id NOT IN ('47eadadd','c4848fd0','a936125b', '9d03358c')\n;"
    }
   ]
  },
  {
   "title": "Relays by Plan Type",
   "type": "timeseries",
   "description": "Source: DWH\n\nDefinition: Total Relays by Plan type by summarized each minute.",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(r.ts, MINUTE) AS time,\n  a.plan_type as plan,\n  count(*)\nFROM `portal-prd-gke-all.RELAYS.D2` r\nJOIN `portal-prd-gke-all.PORTAL.accounts` a ON r.portal_account_id = a.id\nWHERE\n  r.date BETWEEN DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__from:date:seconds}), DAY)) \n                  AND DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__to:date:seconds}), DAY))\n  AND r.ts BETWEEN TIMESTAMP_SECONDS(${__from:date:seconds}) \n                   AND TIMESTAMP_SECONDS(${__to:date:seconds})\n  AND a.id IS NOT NULL\n  AND r.portal_account_id <> '47eadadd'\nGROUP BY \n  time, \n  plan\nORDER BY \n  time\n;"
    }
   ]
  },
  {
   "title": "Top Accounts",
   "type": "table",
   "description": "Source: DWH\n\nDefinition: Top 10 Accounts by Relays",
   "gridPos": { "h": 15, "w": 14, "x": 8, "y": 47 },
   "targets": [
    {
     "project": "portal-prd-gke-all",
     "rawSql": "WITH account_data AS (\n  SELECT distinct(vau.portal_account_id), user_email, plan_type\n  FROM `portal-prd-gke-all.PORTAL.v_account_users` vau\n  WHERE vau.role_name='OWNER'\n)\nSELECT \n  ad.portal_account_id as account_id, \n  ad.user_email as email, \n  ad.plan_type as plan, \n  count(*) as relays\nFROM account_data ad\nJOIN `portal-prd-gke-all.RELAYS.D2` r ON ad.portal_account_id = r.portal_account_id\nWHERE\n  r.date BETWEEN DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__from:date:seconds}), DAY)) \n                  AND DATE(TIMESTAMP_TRUNC(TIMESTAMP_SECONDS(${__to:date:seconds}), DAY))\n  AND r.ts BETWEEN TIMESTAMP_SECONDS(${__from:date:seconds}) \n                   AND TIMESTAMP_SECONDS(${__to:date:seconds})\n  -- filter out grove accounts\n  AND r.portal_account_id not in ('47eadadd', 'abb4dc00')\nGROUP BY \n  account_id, \n  email, \n  plan\n  ORDER BY \n  relays DESC\n  LIMIT 10\n;"
    }
   ]
  }
 ]
}