services:
  path_gateway:
    container_name: path_gateway
    build:
      context: .
      args:
        IMAGE_TAG: ${IMAGE_TAG}
    ports:
      # TODO_IMPROVE: Update the port to match the actual value defined in the config yaml
      - "3000:3000"
    extra_hosts:
      # Allows host machine to access the docker container; required if the
      # full node RPC and gRPC URLs are running or port forwarded to localhost.
      - "host.docker.internal:host-gateway"
    volumes:
      - ./cmd/.config.yaml:/app/.config.yaml
    command: ["./path"]
    # TODO_IMPROVE: add a health check that looks for component ready states from the /healthz endpoint

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/driver/sqlc/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      retries: 3
