FROM golang:1.23.0

# Add runtime dependencies
RUN apt-get -q update && apt-get install -qyy curl jq less ca-certificates tzdata

# Set working directory and prepare directories
WORKDIR /app
RUN mkdir -p /app/config

# This will be overridden by the sync in live_update
COPY bin/path /app/path
RUN chmod +x /app/path

# Command to run
# CMD ["/app/path"]