services:
  path_gateway:
    container_name: path_gateway
    build:
      context: .
      args:
        IMAGE_TAG: ${IMAGE_TAG:-development}
    volumes:
      - ./cmd/.config.yaml:/app/.config.yaml
    command: ["./path"]
    networks:
      - path_network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  envoy:
    image: envoyproxy/envoy:v1.28.6
    container_name: envoy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    depends_on:
      path_gateway:
        condition: service_healthy
    networks:
      - path_network

networks:
  path_network:
