path:
  count: 1
  delve:
    enabled: false
observability:
  enabled: true
  grafana:
    defaultDashboardsEnabled: false
helm_chart_local_repo:
  # DEV_NOTEi: to use a local copy of Helm charts, set the following:
  # 1. enabled: true, and
  # 2. path: the path to the local Helm chart repo
  #
  enabled: false
  path: ../helm-charts
