// Code generated by MockGen. DO NOT EDIT.
// Source: ./router/router.go
//
// Generated by this command:
//
//	mockgen -source=./router/router.go -destination=./router/router_mock_test.go -package=router
//

// Package router is a generated GoMock package.
package router

import (
	context "context"
	http "net/http"
	reflect "reflect"

	devtools "github.com/buildwithgrove/path/metrics/devtools"
	protocol "github.com/buildwithgrove/path/protocol"
	gomock "go.uber.org/mock/gomock"
)

// Mockgateway is a mock of gateway interface.
type Mockgateway struct {
	ctrl     *gomock.Controller
	recorder *MockgatewayMockRecorder
	isgomock struct{}
}

// MockgatewayMockRecorder is the mock recorder for Mockgateway.
type MockgatewayMockRecorder struct {
	mock *Mockgateway
}

// NewMockgateway creates a new mock instance.
func NewMockgateway(ctrl *gomock.Controller) *Mockgateway {
	mock := &Mockgateway{ctrl: ctrl}
	mock.recorder = &MockgatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockgateway) EXPECT() *MockgatewayMockRecorder {
	return m.recorder
}

// HandleServiceRequest mocks base method.
func (m *Mockgateway) HandleServiceRequest(ctx context.Context, httpReq *http.Request, w http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleServiceRequest", ctx, httpReq, w)
}

// HandleServiceRequest indicates an expected call of HandleServiceRequest.
func (mr *MockgatewayMockRecorder) HandleServiceRequest(ctx, httpReq, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleServiceRequest", reflect.TypeOf((*Mockgateway)(nil).HandleServiceRequest), ctx, httpReq, w)
}

// MockinvalidEndpointsReporter is a mock of invalidEndpointsReporter interface.
type MockinvalidEndpointsReporter struct {
	ctrl     *gomock.Controller
	recorder *MockinvalidEndpointsReporterMockRecorder
	isgomock struct{}
}

// MockinvalidEndpointsReporterMockRecorder is the mock recorder for MockinvalidEndpointsReporter.
type MockinvalidEndpointsReporterMockRecorder struct {
	mock *MockinvalidEndpointsReporter
}

// NewMockinvalidEndpointsReporter creates a new mock instance.
func NewMockinvalidEndpointsReporter(ctrl *gomock.Controller) *MockinvalidEndpointsReporter {
	mock := &MockinvalidEndpointsReporter{ctrl: ctrl}
	mock.recorder = &MockinvalidEndpointsReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinvalidEndpointsReporter) EXPECT() *MockinvalidEndpointsReporterMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockinvalidEndpointsReporter) Report(serviceID protocol.ServiceID) devtools.InvalidEndpointResponses {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", serviceID)
	ret0, _ := ret[0].(devtools.InvalidEndpointResponses)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockinvalidEndpointsReporterMockRecorder) Report(serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockinvalidEndpointsReporter)(nil).Report), serviceID)
}
