endpoints:
  # PascalsProdAccount
  252f4b91:                                                                              
    rate_limiting:                                          
      throughput_limit: 30                                  
      capacity_limit: 100000                                   
      capacity_limit_period: "CAPACITY_LIMIT_PERIOD_MONTHLY"
    metadata:
      name: "DO NOT DELETE - E2E Tests"                               
      plan_type: "PLAN_FREE"                               
      account_id: "01ea9eba"                               
      owner_email: "pascal@grove.city"                      
  8418e716:                                               
    auth:
      auth_type: "API_KEY_AUTH"                             
      api_key: "359feb41082723563ea64ea2e59a8071"                                  
    rate_limiting:                                          
        throughput_limit: 30                                  
        capacity_limit: 100000                                   
        capacity_limit_period: "CAPACITY_LIMIT_PERIOD_MONTHLY"
    metadata:
      name: "DO NOT DELETE - PascalsStarterApp"                                        
      plan_type: "PLAN_FREE"                               
      account_id: "01ea9eba"                               
      owner_email: "pascal@grove.city"

  # PascalsEnterpriseAccount
  00d27534:                                                                              
    metadata:
      name: "DO NOT DELETE - PATH E2E Morse App"                               
      plan_type: "PLAN_UNLIMITED"                               
      account_id: "5e6ddc61"                               
      owner_email: "pascal@grove.city"                     
  ea7f9165:                                               
    auth:
      auth_type: "API_KEY_AUTH"                             
      api_key: "ad61cfb38c1e79ab0ba58f9a1b5968f9"                                  
    metadata:
      name: "DO NOT DELETE - PascalsEnterpriseApp"                               
      plan_type: "PLAN_UNLIMITED"                               
      account_id: "5e6ddc61"                               
      owner_email: "pascal@grove.city"

  # PascalsPersonalAccount
  62ecb3ed5e228b693b3e5424:                                                                              
    auth:
      auth_type: "API_KEY_AUTH"                             
      api_key: "0a8462e6dc5c3b2ed19ea7e5bf8c6aac"                                  
    metadata:
      name: "PascalsMetamask"                                  
      plan_type: "PLAN_UNLIMITED"                               
      account_id: "8f2eb408"                               
      owner_email: "pascal@grove.city"                      
