// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: path/qos/framework/endpoint_sanction.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SanctionType identifies different types of endpoint sanctions.
type SanctionType int32

const (
	SanctionType_SANCTION_TYPE_UNSPECIFIED SanctionType = 0
	SanctionType_SANCTION_TYPE_TEMPORARY   SanctionType = 1 // Time-limited exclusion
	SanctionType_SANCTION_TYPE_PERMANENT   SanctionType = 2 // Permanent exclusion
)

// Enum value maps for SanctionType.
var (
	SanctionType_name = map[int32]string{
		0: "SANCTION_TYPE_UNSPECIFIED",
		1: "SANCTION_TYPE_TEMPORARY",
		2: "SANCTION_TYPE_PERMANENT",
	}
	SanctionType_value = map[string]int32{
		"SANCTION_TYPE_UNSPECIFIED": 0,
		"SANCTION_TYPE_TEMPORARY":   1,
		"SANCTION_TYPE_PERMANENT":   2,
	}
)

func (x SanctionType) Enum() *SanctionType {
	p := new(SanctionType)
	*p = x
	return p
}

func (x SanctionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SanctionType) Descriptor() protoreflect.EnumDescriptor {
	return file_path_qos_framework_endpoint_sanction_proto_enumTypes[0].Descriptor()
}

func (SanctionType) Type() protoreflect.EnumType {
	return &file_path_qos_framework_endpoint_sanction_proto_enumTypes[0]
}

func (x SanctionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SanctionType.Descriptor instead.
func (SanctionType) EnumDescriptor() ([]byte, []int) {
	return file_path_qos_framework_endpoint_sanction_proto_rawDescGZIP(), []int{0}
}

// Sanction represents a recommendation to limit endpoint usage.
type Sanction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            SanctionType           `protobuf:"varint,1,opt,name=type,proto3,enum=path.qos.framework.SanctionType" json:"type,omitempty"` // Type of sanction
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                   // Reason for the sanction
	ExpiryTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry_timestamp,json=expiryTimestamp,proto3" json:"expiry_timestamp,omitempty"`
}

func (x *Sanction) Reset() {
	*x = Sanction{}
	mi := &file_path_qos_framework_endpoint_sanction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sanction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sanction) ProtoMessage() {}

func (x *Sanction) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_framework_endpoint_sanction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sanction.ProtoReflect.Descriptor instead.
func (*Sanction) Descriptor() ([]byte, []int) {
	return file_path_qos_framework_endpoint_sanction_proto_rawDescGZIP(), []int{0}
}

func (x *Sanction) GetType() SanctionType {
	if x != nil {
		return x.Type
	}
	return SanctionType_SANCTION_TYPE_UNSPECIFIED
}

func (x *Sanction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Sanction) GetExpiryTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTimestamp
	}
	return nil
}

var File_path_qos_framework_endpoint_sanction_proto protoreflect.FileDescriptor

var file_path_qos_framework_endpoint_sanction_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x71, 0x6f, 0x73, 0x2f, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x61,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x61,
	0x74, 0x68, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x08, 0x53, 0x61, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70,
	0x61, 0x74, 0x68, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x53, 0x61, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x10,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2a, 0x67, 0x0a, 0x0c, 0x53, 0x61, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x41, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x41, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x54, 0x45, 0x4d, 0x50, 0x4f, 0x52, 0x41, 0x52, 0x59, 0x10, 0x01, 0x12,
	0x1b, 0x0a, 0x17, 0x53, 0x41, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x45, 0x52, 0x4d, 0x41, 0x4e, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x77, 0x69, 0x74, 0x68, 0x67, 0x72, 0x6f, 0x76, 0x65, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x6f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x71, 0x6f, 0x73, 0x2f, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_path_qos_framework_endpoint_sanction_proto_rawDescOnce sync.Once
	file_path_qos_framework_endpoint_sanction_proto_rawDescData = file_path_qos_framework_endpoint_sanction_proto_rawDesc
)

func file_path_qos_framework_endpoint_sanction_proto_rawDescGZIP() []byte {
	file_path_qos_framework_endpoint_sanction_proto_rawDescOnce.Do(func() {
		file_path_qos_framework_endpoint_sanction_proto_rawDescData = protoimpl.X.CompressGZIP(file_path_qos_framework_endpoint_sanction_proto_rawDescData)
	})
	return file_path_qos_framework_endpoint_sanction_proto_rawDescData
}

var file_path_qos_framework_endpoint_sanction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_path_qos_framework_endpoint_sanction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_path_qos_framework_endpoint_sanction_proto_goTypes = []any{
	(SanctionType)(0),             // 0: path.qos.framework.SanctionType
	(*Sanction)(nil),              // 1: path.qos.framework.Sanction
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_path_qos_framework_endpoint_sanction_proto_depIdxs = []int32{
	0, // 0: path.qos.framework.Sanction.type:type_name -> path.qos.framework.SanctionType
	2, // 1: path.qos.framework.Sanction.expiry_timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_path_qos_framework_endpoint_sanction_proto_init() }
func file_path_qos_framework_endpoint_sanction_proto_init() {
	if File_path_qos_framework_endpoint_sanction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_path_qos_framework_endpoint_sanction_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_qos_framework_endpoint_sanction_proto_goTypes,
		DependencyIndexes: file_path_qos_framework_endpoint_sanction_proto_depIdxs,
		EnumInfos:         file_path_qos_framework_endpoint_sanction_proto_enumTypes,
		MessageInfos:      file_path_qos_framework_endpoint_sanction_proto_msgTypes,
	}.Build()
	File_path_qos_framework_endpoint_sanction_proto = out.File
	file_path_qos_framework_endpoint_sanction_proto_rawDesc = nil
	file_path_qos_framework_endpoint_sanction_proto_goTypes = nil
	file_path_qos_framework_endpoint_sanction_proto_depIdxs = nil
}
