{
 "title": "Morse Relay Requests",
 "tags": [
  "path",
  "morse",
  "relays"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Morse Relay Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(path_morse_relays_total{container=\"path\", success=\"true\"}) / sum(path_morse_relays_total{container=\"path\"})"
    }
   ]
  },
  {
   "title": "Success Rate by Service ID",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service_id) (path_morse_relays_total{container=\"path\", success=\"true\"}) / sum by(service_id) (path_morse_relays_total{container=\"path\"})"
    }
   ]
  },
  {
   "title": "Session Height Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by(session_height) (path_morse_relays_total{container=\"path\"}))",
     "legendFormat": "Session Height: {{session_height}}"
    }
   ]
  },
  {
   "title": "Top 10 Endpoints with Highest Error Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(10, sum by(endpoint_addr) (path_morse_relay_errors_total{container=\"path\"}) / (sum by(endpoint_addr) (path_morse_relays_total{container=\"path\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top 10 Applications with Highest Error Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(10, sum by(app_address) (path_morse_relay_errors_total{container=\"path\"}) / (sum by(app_address) (path_morse_relays_total{container=\"path\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sanction Types Distribution Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(sanction_type) (path_morse_relay_errors_total{container=\"path\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Sanction Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(sanction_type) (path_morse_relay_errors_total{container=\"path\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Types Distribution Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(error_type) (path_morse_relay_errors_total{container=\"path\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}