apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.32-latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            if [ ! -f /etc/envoy/envoy.yaml ]; then echo 'envoy.yaml not found. Run `make copy-envoy-config` to generate it.' && exit 1; fi; /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy/envoy.yaml
          subPath: envoy.yaml
        ports:
        - containerPort: 3001
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: envoy-proxy
  type: ClusterIP
