# yaml-language-server: $schema=./services.schema.yaml

####################################################
# ---------------- Morse Services ---------------- #
####################################################
services:
  # Arbitrum One (Archival)
  - name: "Morse - F001 (Arbitrum One) Test"
    service_id: "F001"
    service_type: "evm"
    archival: true
    service_params:
      # https://arbiscan.io/address/0xb38e8c17e38363af6ebdcb3dae12e0243582891d
      contract_address: "0xb38e8c17e38363af6ebdcb3dae12e0243582891d"
      contract_start_block: 3100000 # Minimum block for archival tests
      transaction_hash: "0x19c120c94ccd45189cd0f62019d3455886d2cb0ded78ccb2a25a782aa08265c6"
      call_data: "0x18160ddd"

  # Arbitrum Sepolia Testnet (Archival)
  - name: "Morse - F002 (Arbitrum Sepolia Testnet) Test"
    service_id: "F002"
    service_type: "evm"
    archival: true
    service_params:
      # https://sepolia.arbiscan.io/address/0x22b65d0b9b59af4d3ed59f18b9ad53f5f4908b54
      contract_address: "0x22b65d0b9b59af4d3ed59f18b9ad53f5f4908b54"
      contract_start_block: 132000000
      transaction_hash: "0xb08981afe225228be6a09ab0c48db7b6d67c16eaef6734f706870667ede10f04"
      call_data: "0x18160ddd"

  # Avalanche (Archival)
  - name: "Morse - F003 (Avalanche) Test"
    service_id: "F003"
    service_type: "evm"
    archival: true
    service_params:
      # https://avascan.info/blockchain/c/address/0x9f8c163cBA728e99993ABe7495F06c0A3c8Ac8b9
      contract_address: "0x9f8c163cBA728e99993ABe7495F06c0A3c8Ac8b9"
      contract_start_block: 5000000
      transaction_hash: "0x49369b9ca88cc4ff2e917d51505baa0f9cf873f26c980f3831897a2d6637b6a9"
      call_data: "0x18160ddd"

  # Avalanche-DFK (Archival)
  - name: "Morse - F004 (Avalanche-DFK) Test"
    service_id: "F004"
    service_type: "evm"
    archival: true
    service_params:
      # https://avascan.info/blockchain/dfk/address/0xCCb93dABD71c8Dad03Fc4CE5559dC3D89F67a260
      contract_address: "0xCCb93dABD71c8Dad03Fc4CE5559dC3D89F67a260"
      contract_start_block: 45000000
      transaction_hash: "0x74ae8f4f5c0da6c2e0a4a3f336a32f379c664a3e3ca026d799648b1af07a25bc"
      call_data: "0x18160ddd"

  # Base (Archival)
  - name: "Morse - F005 (Base) Test"
    service_id: "F005"
    service_type: "evm"
    archival: true
    service_params:
      # https://basescan.org/address/0x3304e22ddaa22bcdc5fca2269b418046ae7b566a
      contract_address: "0x3304E22DDaa22bCdC5fCa2269b418046aE7b566A"
      contract_start_block: 4504400
      transaction_hash: "0x2d0409ebc63bc12fb1603305541df099be83b8ab788f78a76e1f2ef438cda7a4"
      call_data: "0x18160ddd"

  # Base Sepolia Testnet (Archival)
  - name: "Morse - F006 (Base Sepolia Testnet) Test"
    service_id: "F006"
    service_type: "evm"
    archival: true
    service_params:
      # https://sepolia.basescan.org/address/0xbab76e4365a2dff89ddb2d3fc9994103b48886c0
      contract_address: "0xbab76e4365a2dff89ddb2d3fc9994103b48886c0"
      contract_start_block: 13000000
      transaction_hash: "0xfd2f3009c9b2601f9c29630a695518f9b2923bb0e56dd73dbda94e161c5da75e"
      call_data: "0x18160ddd"

  # Berachain (Archival)
  - name: "Morse - F035 (Berachain) Test"
    service_id: "F035"
    service_type: "evm"
    archival: true
    service_params:
      # https://berascan.com/address/0x6969696969696969696969696969696969696969
      contract_address: "0x6969696969696969696969696969696969696969"
      contract_start_block: 2000000
      transaction_hash: "0x2f45310d00bcf44bac63d154ad830d17da57e8a15f33352637832ae28a384f31"
      call_data: "0x18160ddd"

  # Blast (Archival)
  - name: "Morse - F008 (Blast) Test"
    service_id: "F008"
    service_type: "evm"
    archival: true
    service_params:
      # https://blastscan.io/address/0x4300000000000000000000000000000000000004
      contract_address: "0x4300000000000000000000000000000000000004"
      contract_start_block: 1000000
      transaction_hash: "0x7677003e842f2794abc675caa0ed7a8e913488d4896987f684e3d84a0542d42a"
      call_data: "0x18160ddd"

  # BNB Smart Chain (Archival)
  - name: "Morse - F009 (BNB Smart Chain) Test"
    service_id: "F009"
    service_type: "evm"
    archival: true
    service_params:
      # https://bsctrace.com/address/0xfb50526f49894b78541b776f5aaefe43e3bd8590
      contract_address: "0xfb50526f49894b78541b776f5aaefe43e3bd8590"
      contract_start_block: 33049200
      transaction_hash: "0xa0a4854d8e2d82927dc227000706982b093a90d7f540d46af9b6fda415c49133"
      call_data: "0x18160ddd"

  # Boba (Archival)
  - name: "Morse - F00A (Boba) Test"
    service_id: "F00A"
    service_type: "evm"
    archival: true
    service_params:
      # https://bobascan.com/address/0x3A92cA39476fF84Dc579C868D4D7dE125513B034
      contract_address: "0x3A92cA39476fF84Dc579C868D4D7dE125513B034"
      contract_start_block: 3060300
      transaction_hash: "0x524e3b4f0fad0c00d4b7ef83481f979d2d8ec8c14a9c446f0ad9921fa84f3290"
      call_data: "0x18160ddd"

  # Celo (Archival)
  - name: "Morse - F00B (Celo) Test"
    service_id: "F00B"
    service_type: "evm"
    archival: true
    service_params:
      # https://celo.blockscout.com/address/0xf89d7b9c864f589bbF53a82105107622B35EaA40
      contract_address: "0xf89d7b9c864f589bbF53a82105107622B35EaA40"
      contract_start_block: 20000000
      transaction_hash: "0x9372db804edb06b14e8adaca99379fa24b57b68a1752ea24889b9b12ef16364a"
      call_data: "0x18160ddd"

  # Ethereum Mainnet (Archival)
  - name: "Morse - F00C (Ethereum) Test"
    service_id: "F00C"
    service_type: "evm"
    archival: true
    service_params:
      # https://etherscan.io/address/0x28C6c06298d514Db089934071355E5743bf21d60
      contract_address: "0x28C6c06298d514Db089934071355E5743bf21d60"
      contract_start_block: 12300000 # Minimum block for archival tests
      transaction_hash: "0xfeccd627b5b391d04fe45055873de3b2c0b4302d52e96bd41d5f0019a704165f"
      call_data: "0x18160ddd"

  # Ethereum Holesky Testnet (Archival)
  - name: "Morse - F00D (Ethereum Holesky Testnet) Test"
    service_id: "F00D"
    service_type: "evm"
    archival: true
    service_params:
      # https://holesky.etherscan.io/address/0xc6392ad8a14794ea57d237d12017e7295bea2363
      contract_address: "0xc6392ad8a14794ea57d237d12017e7295bea2363"
      contract_start_block: 1900384
      transaction_hash: "0x9768861c69852b05eae232faea68ec6bf3e593308ac94b85f3206bcdf01f074c"
      call_data: "0x18160ddd"

  # Ethereum Sepolia Testnet (Archival)
  - name: "Morse - F00E (Ethereum Sepolia Testnet) Test"
    service_id: "F00E"
    service_type: "evm"
    archival: true
    service_params:
      # https://sepolia.etherscan.io/address/0xc0f3833b7e7216eecd9f6bc2c7927a7aa36ab58b
      contract_address: "0xc0f3833b7e7216eecd9f6bc2c7927a7aa36ab58b"
      contract_start_block: 6412177
      transaction_hash: "0x1a82131a2caa0f4964661fd6316f2ff16c9a195e9c9befc14766956f957a2e40"
      call_data: "0x18160ddd"

  # Fuse (Archival)
  - name: "Morse - F012 (Fuse) Test"
    service_id: "F012"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.fuse.io/address/0x3014ca10b91cb3D0AD85fEf7A3Cb95BCAc9c0f79
      contract_address: "0x3014ca10b91cb3D0AD85fEf7A3Cb95BCAc9c0f79"
      contract_start_block: 15000000
      transaction_hash: "0x2a0fcdc34a2db7b216f0d637937f8bfab6259fed397164b27896c88ab8f1cc3a"
      call_data: "0x18160ddd"

  # Gnosis (Archival)
  - name: "Morse - F013 (Gnosis) Test"
    service_id: "F013"
    service_type: "evm"
    archival: true
    service_params:
      # https://gnosisscan.io/address/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d
      contract_address: "0xe91d153e0b41518a2ce8dd3d7944fa863463a97d"
      contract_start_block: 20000000
      transaction_hash: "0xd42f4505181e8265428d70489f8ea30fd23d095477d25a4efc47e98315e7611a"
      call_data: "0x18160ddd"

  # Harmony-0 (Archival)
  - name: "Morse - F014 (Harmony-0) Test"
    service_id: "F014"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.harmony.one/address/one19senwle0ezp3he6ed9xkc7zeg5rs94r0ecpp0a?shard=0
      contract_address: "one19senwle0ezp3he6ed9xkc7zeg5rs94r0ecpp0a"
      contract_start_block: 60000000
      transaction_hash: "0x1d1e57d30803dd1d1d2f34805a38cf2c53457fcc456586521315214d78124dbe"
      call_data: "0x18160ddd"

  # Ink (Archival)
  - name: "Morse - F032 (Ink) Test"
    service_id: "F032"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.inkonchain.com/address/0x4200000000000000000000000000000000000006
      contract_address: "0x4200000000000000000000000000000000000006"
      contract_start_block: 4500000
      transaction_hash: "0x50986c32e27b9ebdada3e9711694c67e3e9c9aacf3f3a8792e2d4ab6e37721a7"
      call_data: "0x18160ddd"

  # IoTeX (Archival)
  - name: "Morse - F015 (IoTeX) Test"
    service_id: "F015"
    service_type: "evm"
    archival: true
    service_params:
      # https://iotexscan.io/address/0x0a7f9ea31ca689f346e1661cf73a47c69d4bd883#transactions
      contract_address: "0x0a7f9ea31ca689f346e1661cf73a47c69d4bd883"
      contract_start_block: 6440916
      transaction_hash: "0x4d9b4755a2a1633244724fe6280abb8ea205a093f989581c99214b2bc93f6d71"
      call_data: "0x18160ddd"

  # Kaia (Archival)
  - name: "Morse - F016 (Kaia) Test"
    service_id: "F016"
    service_type: "evm"
    archival: true
    service_params:
      # https://www.kaiascan.io/address/0x0051ef9259c7ec0644a80e866ab748a2f30841b3
      contract_address: "0x0051ef9259c7ec0644a80e866ab748a2f30841b3"
      contract_start_block: 170000000
      transaction_hash: "0x715b318825b38acc868d4323f2d0719209a9c5f5412f59149be90748668900e9"
      call_data: "0x18160ddd"

  # Linea (Archival)
  - name: "Morse - F030 (Linea) Test"
    service_id: "F030"
    service_type: "evm"
    archival: true
    service_params:
      # https://lineascan.build/address/0xf89d7b9c864f589bbf53a82105107622b35eaa40
      contract_address: "0xf89d7b9c864f589bbf53a82105107622b35eaa40"
      contract_start_block: 10000000
      transaction_hash: "0x372b929b92db7976124b17b9bc23d6ced9969b523c8bb6170136d6ecf509e044"
      call_data: "0x18160ddd"

  # Mantle (Archival)
  - name: "Morse - F033 (Mantle) Test"
    service_id: "F033"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.mantle.xyz/address/0x588846213A30fd36244e0ae0eBB2374516dA836C
      contract_address: "0x588846213A30fd36244e0ae0eBB2374516dA836C"
      contract_start_block: 60000000
      transaction_hash: "0xfc30dd922a20302b88108422da4cfc09a82853d896a5f45f4ea777e12136af70"
      call_data: "0x18160ddd"

  # Metis (Archival)
  - name: "Morse - F018 (Metis) Test"
    service_id: "F018"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.metis.io/address/0xfad31cd4d45Ac7C4B5aC6A0044AA05Ca7C017e62
      contract_address: "0xfad31cd4d45Ac7C4B5aC6A0044AA05Ca7C017e62"
      contract_start_block: 15000000
      transaction_hash: "0x37a5f1d7ed25184813012d843d6c7fecef6b93eda38ce7dcef40385cf97e53f9"
      call_data: "0x18160ddd"

  # Moonbeam (Archival)
  - name: "Morse - F019 (Moonbeam) Test"
    service_id: "F019"
    service_type: "evm"
    archival: true
    service_params:
      # https://moonscan.io/address/0xf89d7b9c864f589bbf53a82105107622b35eaa40
      contract_address: "0xf89d7b9c864f589bbf53a82105107622b35eaa40"
      contract_start_block: 677000
      transaction_hash: "0xb5f1c1612dae7d45c321c2a2bcdd74ebc927cdee2c73be7b3004f8219a3ef6c2"
      call_data: "0x18160ddd"

  # Oasys Mainnet (Archival)
  - name: "Morse - F01C (Oasys) Test"
    service_id: "F01C"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.oasys.games/address/0xf89d7b9c864f589bbF53a82105107622B35EaA40
      contract_address: "0xf89d7b9c864f589bbF53a82105107622B35EaA40"
      contract_start_block: 424300
      transaction_hash: "0x7e5904f6f566577718aa3ddfe589bb6d553daaeb183e2bdc63f5bf838fede8ee"
      call_data: "0x18160ddd"

  # Optimism (Archival)
  - name: "Morse - F01D (Optimism) Test"
    service_id: "F01D"
    service_type: "evm"
    archival: true
    service_params:
      # https://optimistic.etherscan.io/address/0xacd03d601e5bb1b275bb94076ff46ed9d753435a
      contract_address: "0xacD03D601e5bB1B275Bb94076fF46ED9D753435A"
      contract_start_block: 8121800
      transaction_hash: "0xb6df4c9d1162c2a0cca5265cda5028c7bfc5ea684aa570583dc287fb5e8ff4ab"
      call_data: "0x18160ddd"

  # Optimism Sepolia Testnet (Archival)
  - name: "Morse - F01E (Optimism Sepolia Testnet) Test"
    service_id: "F01E"
    service_type: "evm"
    archival: true
    service_params:
      # https://sepolia-optimism.etherscan.io/address/0x734d539a7efee15714a2755caa4280e12ef3d7e4
      contract_address: "0x734d539a7efee15714a2755caa4280e12ef3d7e4"
      contract_start_block: 18241388
      transaction_hash: "0x8e251ac315caca5657b3334b42f0ce0dac3285ee2b7a26c6c4223a953e4421a6"
      call_data: "0x18160ddd"

  # opBNB (Archival)
  - name: "Morse - F01F (opBNB) Test"
    service_id: "F01F"
    service_type: "evm"
    archival: true
    service_params:
      # https://opbnbscan.com/address/0x001ceb373c83ae75b9f5cf78fc2aba3e185d09e2
      contract_address: "0x001ceb373c83ae75b9f5cf78fc2aba3e185d09e2"
      contract_start_block: 20000000
      transaction_hash: "0x0ba32af1af31adf7b87ef98c43e228745c66b057621d0d280a5e18d2345bfa08"
      call_data: "0x18160ddd"

  # Polygon Mainnet (Archival)
  - name: "Morse - F021 (Polygon) Test"
    service_id: "F021"
    service_type: "evm"
    archival: true
    service_params:
      # https://polygonscan.com/address/0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270
      contract_address: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
      contract_start_block: 5000000
      transaction_hash: "0xb4f33e8516656d513df5d827323003c7ad1dcbb5bc46dff57c9bebad676fefe4"
      call_data: "0x18160ddd"

  # Polygon Amoy Testnet (Archival)
  - name: "Morse - F022 (Polygon Amoy Testnet) Test"
    service_id: "F022"
    service_type: "evm"
    archival: true
    service_params:
      # https://amoy.polygonscan.com/address/0x54d03ec0c462e9a01f77579c090cde0fc2617817
      contract_address: "0x54d03ec0c462e9a01f77579c090cde0fc2617817"
      contract_start_block: 10453569
      transaction_hash: "0xe08fa05dab3bd47dfffab37d6e50ba0d90b20da2d13d42bee614f843e5dd50f9"
      call_data: "0x18160ddd"

  # Polygon zkEVM (Archival)
  - name: "Morse - F029 (Polygon zkEVM) Test"
    service_id: "F029"
    service_type: "evm"
    archival: true
    service_params:
      # https://zkevm.polygonscan.com/address/0xee1727f5074E747716637e1776B7F7C7133f16b1
      contract_address: "0xee1727f5074E747716637e1776B7F7C7133f16b1"
      contract_start_block: 111
      transaction_hash: "0xb2c6555653b9fc338a35e7acf0308c14276fbb4908b7a875d7658b8bf7aa3ea1"
      call_data: "0x18160ddd"

  # Scroll (Archival)
  - name: "Morse - F024 (Scroll) Test"
    service_id: "F024"
    service_type: "evm"
    archival: true
    service_params:
      # https://scrollscan.com/address/0x5300000000000000000000000000000000000004
      contract_address: "0x5300000000000000000000000000000000000004"
      contract_start_block: 5000000
      transaction_hash: "0xb231663a547a8b3ca6812d1917b76a7b6aac7958111d1726c0a867205a0e50e8"
      call_data: "0x18160ddd"

  # Sonic (Archival)
  - name: "Morse - F02D (Sonic) Test"
    service_id: "F02D"
    service_type: "evm"
    archival: true
    service_params:
      # https://sonicscan.org/address/0xfc00face00000000000000000000000000000000
      contract_address: "0xfc00face00000000000000000000000000000000"
      contract_start_block: 10769279
      transaction_hash: "0x6988194159e13a51811a0c71394f2893904affc33990089690086210e2b402f0"
      call_data: "0x18160ddd"

  # Taiko (Archival)
  - name: "Morse - F027 (Taiko) Test"
    service_id: "F027"
    service_type: "evm"
    archival: true
    service_params:
      # https://taikoscan.io/address/0x1670000000000000000000000000000000000001
      contract_address: "0x1670000000000000000000000000000000000001"
      contract_start_block: 170163
      transaction_hash: "0xac6909d6d947c1f58ce76cca46f25e3177785ce9e9ac658619fc85bb5da8cdb7"
      call_data: "0x18160ddd"

  # Taiko Hekla Testnet (Archival)
  - name: "Morse - F028 (Taiko Hekla Testnet) Test"
    service_id: "F028"
    service_type: "evm"
    archival: true
    service_params:
      # https://hekla.taikoscan.io/address/0x1670090000000000000000000000000000010001
      contract_address: "0x1670090000000000000000000000000000010001"
      contract_start_block: 420139
      transaction_hash: "0x26f8e0bc913775116335b2b379c19e0a044acdbf5d42f149b7ddd288e273dd6d"
      call_data: "0x18160ddd"

  # XRPL EVM Testnet (Archival)
  - name: "Morse - F036 (XRPL EVM Testnet) Test"
    service_id: "F036"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.testnet.xrplevm.org/address/0xc29e2583eD5C77df8792067989Baf9E4CCD4D7fc
      contract_address: "0xc29e2583eD5C77df8792067989Baf9E4CCD4D7fc"
      contract_start_block: 368266
      transaction_hash: "0xa59fde70cac38068dfd87adb1d7eb40200421ebf7075911f83bcdde810e94058"
      call_data: "0x18160ddd"

  # zkLink (Archival)
  - name: "Morse - F02A (zkLink) Test"
    service_id: "F02A"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.zklink.io/address/0xa3cb8648d12bD36e713af27D92968B370D7A9546
      contract_address: "0xa3cb8648d12bD36e713af27D92968B370D7A9546"
      contract_start_block: 5004627
      transaction_hash: "0xb8bd3cb48c0824b0298f62560aeff84a65fef33635d1da758b8376181809e668"
      call_data: "0x18160ddd"

  # zkSync (Archival)
  - name: "Morse - F02B (zkSync) Test"
    service_id: "F02B"
    service_type: "evm"
    archival: true
    service_params:
      # https://explorer.zksync.io/address/0x03AC0b1b952C643d66A4Dc1fBc75118109cC074C
      contract_address: "0x03AC0b1b952C643d66A4Dc1fBc75118109cC074C"
      contract_start_block: 55405668
      transaction_hash: "0xc65cff6db22a350d39d9154be650cd10bd0ca1c143402c51b3c7802f702328b0"
      call_data: "0x18160ddd"

  # Solana
  - name: "Morse - F025 (Solana) Test"
    service_id: "F025"
    service_type: "solana"
    service_params:
      # https://solscan.io/account/FxteHmLwG9nk1eL4pjNve3Eub2goGkkz6g6TbvdmW46a
      contract_address: "FxteHmLwG9nk1eL4pjNve3Eub2goGkkz6g6TbvdmW46a"
      transaction_hash: "4XqrV7zHtv8mHZqsPxueeYc1NodL9nxkdeZJYPtAuw67LszjdYxVgHwUJgBVubuE63ZCToBawe22c8DAAuRdipKs"

  # TODO_IMPROVE(@commoddity): Update the below chains to test for 
  # for archival once configuration is updated in `service_qos_config.go`

  # Berachain Testnet
  - name: "Morse - F031 (Berachain Testnet) Test"
    service_id: "F031"
    service_type: "evm"

  # Evmos
  - name: "Morse - F00F (Evmos) Test"
    service_id: "F00F"
    service_type: "evm"

  # Fantom
  - name: "Morse - F010 (Fantom) Test"
    service_id: "F010"
    service_type: "evm"

  # Fraxtal
  - name: "Morse - F011 (Fraxtal) Test"
    service_id: "F011"
    service_type: "evm"

  # Kava
  - name: "Morse - F017 (Kava) Test"
    service_id: "F017"
    service_type: "evm"

  # Moonriver
  - name: "Morse - F01A (Moonriver) Test"
    service_id: "F01A"
    service_type: "evm"

  # Near
  - name: "Morse - F01B (Near) Test"
    service_id: "F01B"
    service_type: "evm"

  # Radix
  - name: "Morse - F023 (Radix) Test"
    service_id: "F023"
    service_type: "evm"

  # Sei
  - name: "Morse - F034 (Sei) Test"
    service_id: "F034"
    service_type: "evm"

  # Sui
  - name: "Morse - F026 (Sui) Test"
    service_id: "F026"
    service_type: "evm"

  # TRON
  - name: "Morse - F02E (TRON) Test"
    service_id: "F02E"
    service_type: "evm"

  # XRPL EVM Devnet
  - name: "Morse - F02C (XRPL EVM Devnet) Test"
    service_id: "F02C"
    service_type: "evm"