# DEV_NOTE: To use this for local development:
#   1. Run `make config_morse_localnet` to make a local copy
#   2. Update the following three values in `protocol.morse_config`:
#     - `full_node_config.relay_signing_key`
#     - `signed_aats`
#
# This is an example config file to run a local development environment using the Morse protocol as a relayer.
morse_config:
  full_node_config:
    # DO NOT change rpc_url unless you know what you're doing
    url: "https://pocket-rpc.liquify.com"
    # README: relay_signing_key MUST BE replaced with your personal gateway private key secret
    relay_signing_key: "example_relay_signing_key" # ATTENTION: this is a place-holder for a sensitive data item which should never be shared outside your organization.
    http_config:
      retries: 3
      timeout: "5000ms"
    request_config:
      retries: 3
  # README: signed_aats MUST BE replaced with the AATs of your Morse applications.
  # See the following link for more details:
  # https://docs.pokt.network/gateways/host-a-gateway/relay-process#what-are-aats
  signed_aats:
    "example_application_address":
      client_public_key: "example_application_client_public_key"
      application_public_key: "example_application_public_key"
      application_signature: "example_application_signature"

# services is required. At least one service must be configured with a valid id.
# All fields are optional but the id is required.
services:
  "0021":
    # DO NOT change service alias: it is used in the Morse E2E tests to identify the target service.
    alias: "eth-mainnet"
    request_timeout: "3000ms"

# Enable endpoint hydrator to run QoS checks against endpoints of service 0021
hydrator_config:
  service_ids:
    - 0021
