// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: path/qos/cosmos.proto

package qos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CosmosSDKResponseValidationError defines why an endpoint response was rejected.
// Current invalid response types (as of PR #186):
//  1. EmptyResponse - endpoint returned no data
//  2. UnmarshalErr - response failed to parse into expected format
//  3. NoResponse - no responses recorded by the QoS service: probably caused by protocol-level errors
type CosmosSDKResponseValidationError int32

const (
	CosmosSDKResponseValidationError_COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNSPECIFIED CosmosSDKResponseValidationError = 0
	CosmosSDKResponseValidationError_COSMOS_SDK_RESPONSE_VALIDATION_ERROR_EMPTY       CosmosSDKResponseValidationError = 1 // Response with no data.
	CosmosSDKResponseValidationError_COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNMARSHAL   CosmosSDKResponseValidationError = 2 // Response parsing failed
	CosmosSDKResponseValidationError_COSMOS_SDK_RESPONSE_VALIDATION_ERROR_NO_RESPONSE CosmosSDKResponseValidationError = 3 // No response received from any endpoint
)

// Enum value maps for CosmosSDKResponseValidationError.
var (
	CosmosSDKResponseValidationError_name = map[int32]string{
		0: "COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNSPECIFIED",
		1: "COSMOS_SDK_RESPONSE_VALIDATION_ERROR_EMPTY",
		2: "COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNMARSHAL",
		3: "COSMOS_SDK_RESPONSE_VALIDATION_ERROR_NO_RESPONSE",
	}
	CosmosSDKResponseValidationError_value = map[string]int32{
		"COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNSPECIFIED": 0,
		"COSMOS_SDK_RESPONSE_VALIDATION_ERROR_EMPTY":       1,
		"COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNMARSHAL":   2,
		"COSMOS_SDK_RESPONSE_VALIDATION_ERROR_NO_RESPONSE": 3,
	}
)

func (x CosmosSDKResponseValidationError) Enum() *CosmosSDKResponseValidationError {
	p := new(CosmosSDKResponseValidationError)
	*p = x
	return p
}

func (x CosmosSDKResponseValidationError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CosmosSDKResponseValidationError) Descriptor() protoreflect.EnumDescriptor {
	return file_path_qos_cosmos_proto_enumTypes[0].Descriptor()
}

func (CosmosSDKResponseValidationError) Type() protoreflect.EnumType {
	return &file_path_qos_cosmos_proto_enumTypes[0]
}

func (x CosmosSDKResponseValidationError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CosmosSDKResponseValidationError.Descriptor instead.
func (CosmosSDKResponseValidationError) EnumDescriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{0}
}

// CosmosSDKRequestObservations captures all observations made while serving a single CosmosSDK blockchain service request.
type CosmosSDKRequestObservations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CosmosSDK blockchain service's route request, including all params
	RouteRequest string `protobuf:"bytes,1,opt,name=route_request,json=routeRequest,proto3" json:"route_request,omitempty"`
	// chain_id is the blockchain identifier for the QoS implementation.
	// This is preset by the processor and not determined by the request.
	// Used by metrics and data pipeline.
	ChainId string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// service_id is the identifier for the QoS implementation.
	// It is the "alias" or human readable interpretation of the chain_id.
	ServiceId string `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// The origin of the request: user vs. QoS service (requests built by QoS for collecting data on endpoints)
	RequestOrigin RequestOrigin `protobuf:"varint,4,opt,name=request_origin,json=requestOrigin,proto3,enum=path.qos.RequestOrigin" json:"request_origin,omitempty"`
	// Tracks request errors, if any.
	RequestError *RequestError `protobuf:"bytes,5,opt,name=request_error,json=requestError,proto3,oneof" json:"request_error,omitempty"`
	// CosmosSDK-specific observations from endpoint(s) that responded to the service request.
	// Multiple observations may occur when:
	// - Original endpoint fails
	// - Request is sent to additional endpoints for data collection
	EndpointObservations []*CosmosSDKEndpointObservation `protobuf:"bytes,6,rep,name=endpoint_observations,json=endpointObservations,proto3" json:"endpoint_observations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CosmosSDKRequestObservations) Reset() {
	*x = CosmosSDKRequestObservations{}
	mi := &file_path_qos_cosmos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosmosSDKRequestObservations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosSDKRequestObservations) ProtoMessage() {}

func (x *CosmosSDKRequestObservations) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_cosmos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosSDKRequestObservations.ProtoReflect.Descriptor instead.
func (*CosmosSDKRequestObservations) Descriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{0}
}

func (x *CosmosSDKRequestObservations) GetRouteRequest() string {
	if x != nil {
		return x.RouteRequest
	}
	return ""
}

func (x *CosmosSDKRequestObservations) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CosmosSDKRequestObservations) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CosmosSDKRequestObservations) GetRequestOrigin() RequestOrigin {
	if x != nil {
		return x.RequestOrigin
	}
	return RequestOrigin_REQUEST_ORIGIN_UNSPECIFIED
}

func (x *CosmosSDKRequestObservations) GetRequestError() *RequestError {
	if x != nil {
		return x.RequestError
	}
	return nil
}

func (x *CosmosSDKRequestObservations) GetEndpointObservations() []*CosmosSDKEndpointObservation {
	if x != nil {
		return x.EndpointObservations
	}
	return nil
}

// CosmosSDKEndpointObservation stores a single observation from an endpoint servicing the protocol response.
// Example: A Pocket node on Shannon backed by an Ethereum data node servicing an `eth_getBlockNumber` request.
type CosmosSDKEndpointObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address of the endpoint handling the request (e.g., onchain address of a Pocket Morse/Shannon node)
	EndpointAddr string `protobuf:"bytes,1,opt,name=endpoint_addr,json=endpointAddr,proto3" json:"endpoint_addr,omitempty"`
	// Details of the response received from the endpoint
	//
	// Types that are valid to be assigned to ResponseObservation:
	//
	//	*CosmosSDKEndpointObservation_CometbftHealthResponse
	//	*CosmosSDKEndpointObservation_CometbftStatusResponse
	//	*CosmosSDKEndpointObservation_CosmosStatusResponse
	//	*CosmosSDKEndpointObservation_UnrecognizedResponse
	//	*CosmosSDKEndpointObservation_EmptyResponse
	ResponseObservation isCosmosSDKEndpointObservation_ResponseObservation `protobuf_oneof:"response_observation"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CosmosSDKEndpointObservation) Reset() {
	*x = CosmosSDKEndpointObservation{}
	mi := &file_path_qos_cosmos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosmosSDKEndpointObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosSDKEndpointObservation) ProtoMessage() {}

func (x *CosmosSDKEndpointObservation) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_cosmos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosSDKEndpointObservation.ProtoReflect.Descriptor instead.
func (*CosmosSDKEndpointObservation) Descriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{1}
}

func (x *CosmosSDKEndpointObservation) GetEndpointAddr() string {
	if x != nil {
		return x.EndpointAddr
	}
	return ""
}

func (x *CosmosSDKEndpointObservation) GetResponseObservation() isCosmosSDKEndpointObservation_ResponseObservation {
	if x != nil {
		return x.ResponseObservation
	}
	return nil
}

func (x *CosmosSDKEndpointObservation) GetCometbftHealthResponse() *CometBFTHealthResponse {
	if x != nil {
		if x, ok := x.ResponseObservation.(*CosmosSDKEndpointObservation_CometbftHealthResponse); ok {
			return x.CometbftHealthResponse
		}
	}
	return nil
}

func (x *CosmosSDKEndpointObservation) GetCometbftStatusResponse() *CometBFTStatusResponse {
	if x != nil {
		if x, ok := x.ResponseObservation.(*CosmosSDKEndpointObservation_CometbftStatusResponse); ok {
			return x.CometbftStatusResponse
		}
	}
	return nil
}

func (x *CosmosSDKEndpointObservation) GetCosmosStatusResponse() *CosmosSDKStatusResponse {
	if x != nil {
		if x, ok := x.ResponseObservation.(*CosmosSDKEndpointObservation_CosmosStatusResponse); ok {
			return x.CosmosStatusResponse
		}
	}
	return nil
}

func (x *CosmosSDKEndpointObservation) GetUnrecognizedResponse() *CosmosSDKUnrecognizedResponse {
	if x != nil {
		if x, ok := x.ResponseObservation.(*CosmosSDKEndpointObservation_UnrecognizedResponse); ok {
			return x.UnrecognizedResponse
		}
	}
	return nil
}

func (x *CosmosSDKEndpointObservation) GetEmptyResponse() *CosmosSDKEmptyResponse {
	if x != nil {
		if x, ok := x.ResponseObservation.(*CosmosSDKEndpointObservation_EmptyResponse); ok {
			return x.EmptyResponse
		}
	}
	return nil
}

type isCosmosSDKEndpointObservation_ResponseObservation interface {
	isCosmosSDKEndpointObservation_ResponseObservation()
}

type CosmosSDKEndpointObservation_CometbftHealthResponse struct {
	// Response to `/health` request
	CometbftHealthResponse *CometBFTHealthResponse `protobuf:"bytes,2,opt,name=cometbft_health_response,json=cometbftHealthResponse,proto3,oneof"`
}

type CosmosSDKEndpointObservation_CometbftStatusResponse struct {
	// Response to `/status` request
	CometbftStatusResponse *CometBFTStatusResponse `protobuf:"bytes,3,opt,name=cometbft_status_response,json=cometbftStatusResponse,proto3,oneof"`
}

type CosmosSDKEndpointObservation_CosmosStatusResponse struct {
	// Response to `/cosmos/base/node/v1beta1/status` request
	CosmosStatusResponse *CosmosSDKStatusResponse `protobuf:"bytes,4,opt,name=cosmos_status_response,json=cosmosStatusResponse,proto3,oneof"`
}

type CosmosSDKEndpointObservation_UnrecognizedResponse struct {
	// Responses not used in endpoint validation
	UnrecognizedResponse *CosmosSDKUnrecognizedResponse `protobuf:"bytes,5,opt,name=unrecognized_response,json=unrecognizedResponse,proto3,oneof"`
}

type CosmosSDKEndpointObservation_EmptyResponse struct {
	// CosmosSDKEmptyResponse indicates an endpoint returned no data.
	// Used to:
	//   - Disqualify endpoints that return empty responses
	//   - Track metrics for empty response patterns
	EmptyResponse *CosmosSDKEmptyResponse `protobuf:"bytes,6,opt,name=empty_response,json=emptyResponse,proto3,oneof"`
}

func (*CosmosSDKEndpointObservation_CometbftHealthResponse) isCosmosSDKEndpointObservation_ResponseObservation() {
}

func (*CosmosSDKEndpointObservation_CometbftStatusResponse) isCosmosSDKEndpointObservation_ResponseObservation() {
}

func (*CosmosSDKEndpointObservation_CosmosStatusResponse) isCosmosSDKEndpointObservation_ResponseObservation() {
}

func (*CosmosSDKEndpointObservation_UnrecognizedResponse) isCosmosSDKEndpointObservation_ResponseObservation() {
}

func (*CosmosSDKEndpointObservation_EmptyResponse) isCosmosSDKEndpointObservation_ResponseObservation() {
}

// CometBFTHealthResponse stores the response to a `health` request
// Reference: https://docs.cometbft.com/v1.0/spec/rpc/#health
type CometBFTHealthResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HealthStatusResponse bool                   `protobuf:"varint,1,opt,name=health_status_response,json=healthStatusResponse,proto3" json:"health_status_response,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CometBFTHealthResponse) Reset() {
	*x = CometBFTHealthResponse{}
	mi := &file_path_qos_cosmos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CometBFTHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometBFTHealthResponse) ProtoMessage() {}

func (x *CometBFTHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_cosmos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometBFTHealthResponse.ProtoReflect.Descriptor instead.
func (*CometBFTHealthResponse) Descriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{2}
}

func (x *CometBFTHealthResponse) GetHealthStatusResponse() bool {
	if x != nil {
		return x.HealthStatusResponse
	}
	return false
}

// CometBFTStatusResponse stores the latest block number from a `/status` request
// Reference: https://docs.cometbft.com/v1.0/spec/rpc/#status
type CometBFTStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chain ID of the endpoint. Comes from the `NodeInfo.Network` field in the `/status` response.
	// Reference: https://docs.cometbft.com/v1.0/spec/rpc/#status
	ChainIdResponse string `protobuf:"bytes,1,opt,name=chain_id_response,json=chainIdResponse,proto3" json:"chain_id_response,omitempty"`
	// Indicates if the endpoint is catching up to the network.
	// Comes from the `SyncInfo.CatchingUp` field in the `/status` response.
	// Reference: https://docs.cometbft.com/v1.0/spec/rpc/#status
	CatchingUpResponse bool `protobuf:"varint,2,opt,name=catching_up_response,json=catchingUpResponse,proto3" json:"catching_up_response,omitempty"`
	// Latest block height of the endpoint.
	// Comes from the `SyncInfo.LatestBlockHeight` field in the `/status` response.
	// Reference: https://docs.cometbft.com/v1.0/spec/rpc/#status
	LatestBlockHeightResponse string `protobuf:"bytes,3,opt,name=latest_block_height_response,json=latestBlockHeightResponse,proto3" json:"latest_block_height_response,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CometBFTStatusResponse) Reset() {
	*x = CometBFTStatusResponse{}
	mi := &file_path_qos_cosmos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CometBFTStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometBFTStatusResponse) ProtoMessage() {}

func (x *CometBFTStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_cosmos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometBFTStatusResponse.ProtoReflect.Descriptor instead.
func (*CometBFTStatusResponse) Descriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{3}
}

func (x *CometBFTStatusResponse) GetChainIdResponse() string {
	if x != nil {
		return x.ChainIdResponse
	}
	return ""
}

func (x *CometBFTStatusResponse) GetCatchingUpResponse() bool {
	if x != nil {
		return x.CatchingUpResponse
	}
	return false
}

func (x *CometBFTStatusResponse) GetLatestBlockHeightResponse() string {
	if x != nil {
		return x.LatestBlockHeightResponse
	}
	return ""
}

// CosmosSDKStatusResponse stores the latest block number from a `/cosmos/base/node/v1beta1/status` request
// Reference: https://docs.cosmos.network/api#tag/Service/operation/Status
type CosmosSDKStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latest block height of the endpoint.
	// Comes from the `Height` field in the `/cosmos/base/node/v1beta1/status` response.
	// Reference: https://docs.cosmos.network/api#tag/Service/operation/Status
	LatestBlockHeightResponse uint64 `protobuf:"varint,1,opt,name=latest_block_height_response,json=latestBlockHeightResponse,proto3" json:"latest_block_height_response,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CosmosSDKStatusResponse) Reset() {
	*x = CosmosSDKStatusResponse{}
	mi := &file_path_qos_cosmos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosmosSDKStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosSDKStatusResponse) ProtoMessage() {}

func (x *CosmosSDKStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_cosmos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosSDKStatusResponse.ProtoReflect.Descriptor instead.
func (*CosmosSDKStatusResponse) Descriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{4}
}

func (x *CosmosSDKStatusResponse) GetLatestBlockHeightResponse() uint64 {
	if x != nil {
		return x.LatestBlockHeightResponse
	}
	return 0
}

// CosmosSDKUnrecognizedResponse handles requests with methods ignored by state update
// and endpoint validation
type CosmosSDKUnrecognizedResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JsonrpcResponse *JsonRpcResponse       `protobuf:"bytes,1,opt,name=jsonrpc_response,json=jsonrpcResponse,proto3" json:"jsonrpc_response,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CosmosSDKUnrecognizedResponse) Reset() {
	*x = CosmosSDKUnrecognizedResponse{}
	mi := &file_path_qos_cosmos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosmosSDKUnrecognizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosSDKUnrecognizedResponse) ProtoMessage() {}

func (x *CosmosSDKUnrecognizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_cosmos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosSDKUnrecognizedResponse.ProtoReflect.Descriptor instead.
func (*CosmosSDKUnrecognizedResponse) Descriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{5}
}

func (x *CosmosSDKUnrecognizedResponse) GetJsonrpcResponse() *JsonRpcResponse {
	if x != nil {
		return x.JsonrpcResponse
	}
	return nil
}

// CosmosSDKEmptyResponse indicates an endpoint returned no data.
// Used to:
//   - Disqualify endpoints that return empty responses
//   - Track metrics for empty response patterns
type CosmosSDKEmptyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HttpStatusCode int32                  `protobuf:"varint,1,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	// Always set to EMPTY for empty responses
	ResponseValidationError CosmosSDKResponseValidationError `protobuf:"varint,2,opt,name=response_validation_error,json=responseValidationError,proto3,enum=path.qos.CosmosSDKResponseValidationError" json:"response_validation_error,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CosmosSDKEmptyResponse) Reset() {
	*x = CosmosSDKEmptyResponse{}
	mi := &file_path_qos_cosmos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosmosSDKEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosSDKEmptyResponse) ProtoMessage() {}

func (x *CosmosSDKEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_cosmos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosSDKEmptyResponse.ProtoReflect.Descriptor instead.
func (*CosmosSDKEmptyResponse) Descriptor() ([]byte, []int) {
	return file_path_qos_cosmos_proto_rawDescGZIP(), []int{6}
}

func (x *CosmosSDKEmptyResponse) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

func (x *CosmosSDKEmptyResponse) GetResponseValidationError() CosmosSDKResponseValidationError {
	if x != nil {
		return x.ResponseValidationError
	}
	return CosmosSDKResponseValidationError_COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNSPECIFIED
}

var File_path_qos_cosmos_proto protoreflect.FileDescriptor

const file_path_qos_cosmos_proto_rawDesc = "" +
	"\n" +
	"\x15path/qos/cosmos.proto\x12\bpath.qos\x1a\x16path/qos/jsonrpc.proto\x1a\x1dpath/qos/request_origin.proto\x1a\x1cpath/qos/request_error.proto\"\xee\x02\n" +
	"\x1cCosmosSDKRequestObservations\x12#\n" +
	"\rroute_request\x18\x01 \x01(\tR\frouteRequest\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12>\n" +
	"\x0erequest_origin\x18\x04 \x01(\x0e2\x17.path.qos.RequestOriginR\rrequestOrigin\x12@\n" +
	"\rrequest_error\x18\x05 \x01(\v2\x16.path.qos.RequestErrorH\x00R\frequestError\x88\x01\x01\x12[\n" +
	"\x15endpoint_observations\x18\x06 \x03(\v2&.path.qos.CosmosSDKEndpointObservationR\x14endpointObservationsB\x10\n" +
	"\x0e_request_error\"\x9d\x04\n" +
	"\x1cCosmosSDKEndpointObservation\x12#\n" +
	"\rendpoint_addr\x18\x01 \x01(\tR\fendpointAddr\x12\\\n" +
	"\x18cometbft_health_response\x18\x02 \x01(\v2 .path.qos.CometBFTHealthResponseH\x00R\x16cometbftHealthResponse\x12\\\n" +
	"\x18cometbft_status_response\x18\x03 \x01(\v2 .path.qos.CometBFTStatusResponseH\x00R\x16cometbftStatusResponse\x12Y\n" +
	"\x16cosmos_status_response\x18\x04 \x01(\v2!.path.qos.CosmosSDKStatusResponseH\x00R\x14cosmosStatusResponse\x12^\n" +
	"\x15unrecognized_response\x18\x05 \x01(\v2'.path.qos.CosmosSDKUnrecognizedResponseH\x00R\x14unrecognizedResponse\x12I\n" +
	"\x0eempty_response\x18\x06 \x01(\v2 .path.qos.CosmosSDKEmptyResponseH\x00R\remptyResponseB\x16\n" +
	"\x14response_observation\"N\n" +
	"\x16CometBFTHealthResponse\x124\n" +
	"\x16health_status_response\x18\x01 \x01(\bR\x14healthStatusResponse\"\xb7\x01\n" +
	"\x16CometBFTStatusResponse\x12*\n" +
	"\x11chain_id_response\x18\x01 \x01(\tR\x0fchainIdResponse\x120\n" +
	"\x14catching_up_response\x18\x02 \x01(\bR\x12catchingUpResponse\x12?\n" +
	"\x1clatest_block_height_response\x18\x03 \x01(\tR\x19latestBlockHeightResponse\"Z\n" +
	"\x17CosmosSDKStatusResponse\x12?\n" +
	"\x1clatest_block_height_response\x18\x01 \x01(\x04R\x19latestBlockHeightResponse\"e\n" +
	"\x1dCosmosSDKUnrecognizedResponse\x12D\n" +
	"\x10jsonrpc_response\x18\x01 \x01(\v2\x19.path.qos.JsonRpcResponseR\x0fjsonrpcResponse\"\xaa\x01\n" +
	"\x16CosmosSDKEmptyResponse\x12(\n" +
	"\x10http_status_code\x18\x01 \x01(\x05R\x0ehttpStatusCode\x12f\n" +
	"\x19response_validation_error\x18\x02 \x01(\x0e2*.path.qos.CosmosSDKResponseValidationErrorR\x17responseValidationError*\xf2\x01\n" +
	" CosmosSDKResponseValidationError\x124\n" +
	"0COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNSPECIFIED\x10\x00\x12.\n" +
	"*COSMOS_SDK_RESPONSE_VALIDATION_ERROR_EMPTY\x10\x01\x122\n" +
	".COSMOS_SDK_RESPONSE_VALIDATION_ERROR_UNMARSHAL\x10\x02\x124\n" +
	"0COSMOS_SDK_RESPONSE_VALIDATION_ERROR_NO_RESPONSE\x10\x03B0Z.github.com/buildwithgrove/path/observation/qosb\x06proto3"

var (
	file_path_qos_cosmos_proto_rawDescOnce sync.Once
	file_path_qos_cosmos_proto_rawDescData []byte
)

func file_path_qos_cosmos_proto_rawDescGZIP() []byte {
	file_path_qos_cosmos_proto_rawDescOnce.Do(func() {
		file_path_qos_cosmos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_path_qos_cosmos_proto_rawDesc), len(file_path_qos_cosmos_proto_rawDesc)))
	})
	return file_path_qos_cosmos_proto_rawDescData
}

var file_path_qos_cosmos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_path_qos_cosmos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_path_qos_cosmos_proto_goTypes = []any{
	(CosmosSDKResponseValidationError)(0), // 0: path.qos.CosmosSDKResponseValidationError
	(*CosmosSDKRequestObservations)(nil),  // 1: path.qos.CosmosSDKRequestObservations
	(*CosmosSDKEndpointObservation)(nil),  // 2: path.qos.CosmosSDKEndpointObservation
	(*CometBFTHealthResponse)(nil),        // 3: path.qos.CometBFTHealthResponse
	(*CometBFTStatusResponse)(nil),        // 4: path.qos.CometBFTStatusResponse
	(*CosmosSDKStatusResponse)(nil),       // 5: path.qos.CosmosSDKStatusResponse
	(*CosmosSDKUnrecognizedResponse)(nil), // 6: path.qos.CosmosSDKUnrecognizedResponse
	(*CosmosSDKEmptyResponse)(nil),        // 7: path.qos.CosmosSDKEmptyResponse
	(RequestOrigin)(0),                    // 8: path.qos.RequestOrigin
	(*RequestError)(nil),                  // 9: path.qos.RequestError
	(*JsonRpcResponse)(nil),               // 10: path.qos.JsonRpcResponse
}
var file_path_qos_cosmos_proto_depIdxs = []int32{
	8,  // 0: path.qos.CosmosSDKRequestObservations.request_origin:type_name -> path.qos.RequestOrigin
	9,  // 1: path.qos.CosmosSDKRequestObservations.request_error:type_name -> path.qos.RequestError
	2,  // 2: path.qos.CosmosSDKRequestObservations.endpoint_observations:type_name -> path.qos.CosmosSDKEndpointObservation
	3,  // 3: path.qos.CosmosSDKEndpointObservation.cometbft_health_response:type_name -> path.qos.CometBFTHealthResponse
	4,  // 4: path.qos.CosmosSDKEndpointObservation.cometbft_status_response:type_name -> path.qos.CometBFTStatusResponse
	5,  // 5: path.qos.CosmosSDKEndpointObservation.cosmos_status_response:type_name -> path.qos.CosmosSDKStatusResponse
	6,  // 6: path.qos.CosmosSDKEndpointObservation.unrecognized_response:type_name -> path.qos.CosmosSDKUnrecognizedResponse
	7,  // 7: path.qos.CosmosSDKEndpointObservation.empty_response:type_name -> path.qos.CosmosSDKEmptyResponse
	10, // 8: path.qos.CosmosSDKUnrecognizedResponse.jsonrpc_response:type_name -> path.qos.JsonRpcResponse
	0,  // 9: path.qos.CosmosSDKEmptyResponse.response_validation_error:type_name -> path.qos.CosmosSDKResponseValidationError
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_path_qos_cosmos_proto_init() }
func file_path_qos_cosmos_proto_init() {
	if File_path_qos_cosmos_proto != nil {
		return
	}
	file_path_qos_jsonrpc_proto_init()
	file_path_qos_request_origin_proto_init()
	file_path_qos_request_error_proto_init()
	file_path_qos_cosmos_proto_msgTypes[0].OneofWrappers = []any{}
	file_path_qos_cosmos_proto_msgTypes[1].OneofWrappers = []any{
		(*CosmosSDKEndpointObservation_CometbftHealthResponse)(nil),
		(*CosmosSDKEndpointObservation_CometbftStatusResponse)(nil),
		(*CosmosSDKEndpointObservation_CosmosStatusResponse)(nil),
		(*CosmosSDKEndpointObservation_UnrecognizedResponse)(nil),
		(*CosmosSDKEndpointObservation_EmptyResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_path_qos_cosmos_proto_rawDesc), len(file_path_qos_cosmos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_qos_cosmos_proto_goTypes,
		DependencyIndexes: file_path_qos_cosmos_proto_depIdxs,
		EnumInfos:         file_path_qos_cosmos_proto_enumTypes,
		MessageInfos:      file_path_qos_cosmos_proto_msgTypes,
	}.Build()
	File_path_qos_cosmos_proto = out.File
	file_path_qos_cosmos_proto_goTypes = nil
	file_path_qos_cosmos_proto_depIdxs = nil
}
