// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: path/qos/endpoint_selection_metadata.proto

// TODO_TECHDEBT(@adshmh): Package name "path.qos" should be suffixed with a correctly formed version, such as "path.qos.v1"

package qos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndpointSelectionMetadata captures metadata about the endpoint selection process.
// This message can be embedded in various QoS observation types to provide
// consistent endpoint selection tracking across different blockchain services.
type EndpointSelectionMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// random_endpoint_fallback indicates random endpoint selection was used
	// when all available endpoints failed QoS validation.
	RandomEndpointFallback bool `protobuf:"varint,1,opt,name=random_endpoint_fallback,json=randomEndpointFallback,proto3" json:"random_endpoint_fallback,omitempty"`
	// available_endpoints_count is the total number of endpoints available for selection.
	AvailableEndpointsCount uint32 `protobuf:"varint,2,opt,name=available_endpoints_count,json=availableEndpointsCount,proto3" json:"available_endpoints_count,omitempty"`
	// valid_endpoints_count is the number of endpoints that passed validation.
	ValidEndpointsCount uint32 `protobuf:"varint,3,opt,name=valid_endpoints_count,json=validEndpointsCount,proto3" json:"valid_endpoints_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EndpointSelectionMetadata) Reset() {
	*x = EndpointSelectionMetadata{}
	mi := &file_path_qos_endpoint_selection_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSelectionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSelectionMetadata) ProtoMessage() {}

func (x *EndpointSelectionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_endpoint_selection_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSelectionMetadata.ProtoReflect.Descriptor instead.
func (*EndpointSelectionMetadata) Descriptor() ([]byte, []int) {
	return file_path_qos_endpoint_selection_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointSelectionMetadata) GetRandomEndpointFallback() bool {
	if x != nil {
		return x.RandomEndpointFallback
	}
	return false
}

func (x *EndpointSelectionMetadata) GetAvailableEndpointsCount() uint32 {
	if x != nil {
		return x.AvailableEndpointsCount
	}
	return 0
}

func (x *EndpointSelectionMetadata) GetValidEndpointsCount() uint32 {
	if x != nil {
		return x.ValidEndpointsCount
	}
	return 0
}

var File_path_qos_endpoint_selection_metadata_proto protoreflect.FileDescriptor

const file_path_qos_endpoint_selection_metadata_proto_rawDesc = "" +
	"\n" +
	"*path/qos/endpoint_selection_metadata.proto\x12\bpath.qos\"\xc5\x01\n" +
	"\x19EndpointSelectionMetadata\x128\n" +
	"\x18random_endpoint_fallback\x18\x01 \x01(\bR\x16randomEndpointFallback\x12:\n" +
	"\x19available_endpoints_count\x18\x02 \x01(\rR\x17availableEndpointsCount\x122\n" +
	"\x15valid_endpoints_count\x18\x03 \x01(\rR\x13validEndpointsCountB0Z.github.com/buildwithgrove/path/observation/qosb\x06proto3"

var (
	file_path_qos_endpoint_selection_metadata_proto_rawDescOnce sync.Once
	file_path_qos_endpoint_selection_metadata_proto_rawDescData []byte
)

func file_path_qos_endpoint_selection_metadata_proto_rawDescGZIP() []byte {
	file_path_qos_endpoint_selection_metadata_proto_rawDescOnce.Do(func() {
		file_path_qos_endpoint_selection_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_path_qos_endpoint_selection_metadata_proto_rawDesc), len(file_path_qos_endpoint_selection_metadata_proto_rawDesc)))
	})
	return file_path_qos_endpoint_selection_metadata_proto_rawDescData
}

var file_path_qos_endpoint_selection_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_path_qos_endpoint_selection_metadata_proto_goTypes = []any{
	(*EndpointSelectionMetadata)(nil), // 0: path.qos.EndpointSelectionMetadata
}
var file_path_qos_endpoint_selection_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_path_qos_endpoint_selection_metadata_proto_init() }
func file_path_qos_endpoint_selection_metadata_proto_init() {
	if File_path_qos_endpoint_selection_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_path_qos_endpoint_selection_metadata_proto_rawDesc), len(file_path_qos_endpoint_selection_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_qos_endpoint_selection_metadata_proto_goTypes,
		DependencyIndexes: file_path_qos_endpoint_selection_metadata_proto_depIdxs,
		MessageInfos:      file_path_qos_endpoint_selection_metadata_proto_msgTypes,
	}.Build()
	File_path_qos_endpoint_selection_metadata_proto = out.File
	file_path_qos_endpoint_selection_metadata_proto_goTypes = nil
	file_path_qos_endpoint_selection_metadata_proto_depIdxs = nil
}
