// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: path/qos/observations.proto

package qos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Observations defines the top-level QoS observations regarding a service request.
// As of PR #72, an entry should be added under `service_observations` for any new Service QoS implementation:
type Observations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service_observations holds the observations of the QoS instance matching the service request.
	// As of PR #72, the two QoS implementations with observations are:
	//  1. Solana blockchain service QoS
	//  2. EVM blockchains service QoS
	//
	// Types that are valid to be assigned to ServiceObservations:
	//
	//	*Observations_Solana
	//	*Observations_EVM
	ServiceObservations isObservations_ServiceObservations `protobuf_oneof:"service_observations"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Observations) Reset() {
	*x = Observations{}
	mi := &file_path_qos_observations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observations) ProtoMessage() {}

func (x *Observations) ProtoReflect() protoreflect.Message {
	mi := &file_path_qos_observations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observations.ProtoReflect.Descriptor instead.
func (*Observations) Descriptor() ([]byte, []int) {
	return file_path_qos_observations_proto_rawDescGZIP(), []int{0}
}

func (x *Observations) GetServiceObservations() isObservations_ServiceObservations {
	if x != nil {
		return x.ServiceObservations
	}
	return nil
}

func (x *Observations) GetSolana() *SolanaRequestObservations {
	if x != nil {
		if x, ok := x.ServiceObservations.(*Observations_Solana); ok {
			return x.Solana
		}
	}
	return nil
}

func (x *Observations) GetEVM() *EVMRequestObservations {
	if x != nil {
		if x, ok := x.ServiceObservations.(*Observations_EVM); ok {
			return x.EVM
		}
	}
	return nil
}

type isObservations_ServiceObservations interface {
	isObservations_ServiceObservations()
}

type Observations_Solana struct {
	// solana holds all the observations, made when serving a SINGLE request, specific to the Solana blockchain service QoS.
	Solana *SolanaRequestObservations `protobuf:"bytes,1,opt,name=solana,proto3,oneof"`
}

type Observations_EVM struct {
	// evm holds all the observations, made when serving a SINGLE request, specific to EVM blockchain service QoS.
	EVM *EVMRequestObservations `protobuf:"bytes,2,opt,name=EVM,proto3,oneof"`
}

func (*Observations_Solana) isObservations_ServiceObservations() {}

func (*Observations_EVM) isObservations_ServiceObservations() {}

var File_path_qos_observations_proto protoreflect.FileDescriptor

var file_path_qos_observations_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x71, 0x6f, 0x73, 0x2f, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x61, 0x74, 0x68, 0x2e, 0x71, 0x6f, 0x73, 0x1a, 0x12, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x71, 0x6f,
	0x73, 0x2f, 0x65, 0x76, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x61, 0x74,
	0x68, 0x2f, 0x71, 0x6f, 0x73, 0x2f, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x0c, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x53,
	0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x6f, 0x6c, 0x61,
	0x6e, 0x61, 0x12, 0x34, 0x0a, 0x03, 0x45, 0x56, 0x4d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x45, 0x56, 0x4d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x48, 0x00, 0x52, 0x03, 0x45, 0x56, 0x4d, 0x42, 0x16, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x77, 0x69, 0x74, 0x68, 0x67, 0x72, 0x6f, 0x76, 0x65, 0x2f, 0x70, 0x61,
	0x74, 0x68, 0x2f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x71,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_path_qos_observations_proto_rawDescOnce sync.Once
	file_path_qos_observations_proto_rawDescData = file_path_qos_observations_proto_rawDesc
)

func file_path_qos_observations_proto_rawDescGZIP() []byte {
	file_path_qos_observations_proto_rawDescOnce.Do(func() {
		file_path_qos_observations_proto_rawDescData = protoimpl.X.CompressGZIP(file_path_qos_observations_proto_rawDescData)
	})
	return file_path_qos_observations_proto_rawDescData
}

var file_path_qos_observations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_path_qos_observations_proto_goTypes = []any{
	(*Observations)(nil),              // 0: path.qos.Observations
	(*SolanaRequestObservations)(nil), // 1: path.qos.SolanaRequestObservations
	(*EVMRequestObservations)(nil),    // 2: path.qos.EVMRequestObservations
}
var file_path_qos_observations_proto_depIdxs = []int32{
	1, // 0: path.qos.Observations.solana:type_name -> path.qos.SolanaRequestObservations
	2, // 1: path.qos.Observations.EVM:type_name -> path.qos.EVMRequestObservations
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_path_qos_observations_proto_init() }
func file_path_qos_observations_proto_init() {
	if File_path_qos_observations_proto != nil {
		return
	}
	file_path_qos_evm_proto_init()
	file_path_qos_solana_proto_init()
	file_path_qos_observations_proto_msgTypes[0].OneofWrappers = []any{
		(*Observations_Solana)(nil),
		(*Observations_EVM)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_path_qos_observations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_qos_observations_proto_goTypes,
		DependencyIndexes: file_path_qos_observations_proto_depIdxs,
		MessageInfos:      file_path_qos_observations_proto_msgTypes,
	}.Build()
	File_path_qos_observations_proto = out.File
	file_path_qos_observations_proto_rawDesc = nil
	file_path_qos_observations_proto_goTypes = nil
	file_path_qos_observations_proto_depIdxs = nil
}
