// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: path/qos/request_origin.proto

package qos

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO_DOCUMENT(@Olshansk): Standardize the language on organic vs synthetic requests across docs/comments/code.
//
// RequestOrigin enumerates possible request origins:
// - Organic: the request was sent to PATH by a user
// - Synthetic: the request was built by the QoS service to collect data points on an endpoint.
type RequestOrigin int32

const (
	RequestOrigin_REQUEST_ORIGIN_UNSPECIFIED RequestOrigin = 0
	RequestOrigin_REQUEST_ORIGIN_ORGANIC     RequestOrigin = 1 // Organic request, i.e. sent by user.
	RequestOrigin_REQUEST_ORIGIN_SYNTHETIC   RequestOrigin = 2 // Synthetic request, i.e. generated by the QoS Service.
)

// Enum value maps for RequestOrigin.
var (
	RequestOrigin_name = map[int32]string{
		0: "REQUEST_ORIGIN_UNSPECIFIED",
		1: "REQUEST_ORIGIN_ORGANIC",
		2: "REQUEST_ORIGIN_SYNTHETIC",
	}
	RequestOrigin_value = map[string]int32{
		"REQUEST_ORIGIN_UNSPECIFIED": 0,
		"REQUEST_ORIGIN_ORGANIC":     1,
		"REQUEST_ORIGIN_SYNTHETIC":   2,
	}
)

func (x RequestOrigin) Enum() *RequestOrigin {
	p := new(RequestOrigin)
	*p = x
	return p
}

func (x RequestOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_path_qos_request_origin_proto_enumTypes[0].Descriptor()
}

func (RequestOrigin) Type() protoreflect.EnumType {
	return &file_path_qos_request_origin_proto_enumTypes[0]
}

func (x RequestOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestOrigin.Descriptor instead.
func (RequestOrigin) EnumDescriptor() ([]byte, []int) {
	return file_path_qos_request_origin_proto_rawDescGZIP(), []int{0}
}

var File_path_qos_request_origin_proto protoreflect.FileDescriptor

var file_path_qos_request_origin_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x71, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x71, 0x6f, 0x73, 0x2a, 0x69, 0x0a, 0x0d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4f, 0x52, 0x49, 0x47, 0x49, 0x4e, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4f, 0x52, 0x49, 0x47, 0x49, 0x4e, 0x5f, 0x4f, 0x52, 0x47,
	0x41, 0x4e, 0x49, 0x43, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x5f, 0x4f, 0x52, 0x49, 0x47, 0x49, 0x4e, 0x5f, 0x53, 0x59, 0x4e, 0x54, 0x48, 0x45, 0x54,
	0x49, 0x43, 0x10, 0x02, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x77, 0x69, 0x74, 0x68, 0x67, 0x72, 0x6f, 0x76,
	0x65, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x71, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_path_qos_request_origin_proto_rawDescOnce sync.Once
	file_path_qos_request_origin_proto_rawDescData = file_path_qos_request_origin_proto_rawDesc
)

func file_path_qos_request_origin_proto_rawDescGZIP() []byte {
	file_path_qos_request_origin_proto_rawDescOnce.Do(func() {
		file_path_qos_request_origin_proto_rawDescData = protoimpl.X.CompressGZIP(file_path_qos_request_origin_proto_rawDescData)
	})
	return file_path_qos_request_origin_proto_rawDescData
}

var file_path_qos_request_origin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_path_qos_request_origin_proto_goTypes = []any{
	(RequestOrigin)(0), // 0: path.qos.RequestOrigin
}
var file_path_qos_request_origin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_path_qos_request_origin_proto_init() }
func file_path_qos_request_origin_proto_init() {
	if File_path_qos_request_origin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_path_qos_request_origin_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_qos_request_origin_proto_goTypes,
		DependencyIndexes: file_path_qos_request_origin_proto_depIdxs,
		EnumInfos:         file_path_qos_request_origin_proto_enumTypes,
	}.Build()
	File_path_qos_request_origin_proto = out.File
	file_path_qos_request_origin_proto_rawDesc = nil
	file_path_qos_request_origin_proto_goTypes = nil
	file_path_qos_request_origin_proto_depIdxs = nil
}
