// Package portaldb provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package portaldb

// Defines values for PreferParams.
const (
	PreferParamsParamsSingleObject PreferParams = "params=single-object"
)

// Defines values for PostRpcArmorParamsPrefer.
const (
	PostRpcArmorParamsPreferParamsSingleObject PostRpcArmorParamsPrefer = "params=single-object"
)

// Defines values for PostRpcDearmorParamsPrefer.
const (
	PostRpcDearmorParamsPreferParamsSingleObject PostRpcDearmorParamsPrefer = "params=single-object"
)

// Defines values for PostRpcGenRandomUuidParamsPrefer.
const (
	PostRpcGenRandomUuidParamsPreferParamsSingleObject PostRpcGenRandomUuidParamsPrefer = "params=single-object"
)

// Defines values for PostRpcGenSaltParamsPrefer.
const (
	PostRpcGenSaltParamsPreferParamsSingleObject PostRpcGenSaltParamsPrefer = "params=single-object"
)

// Defines values for PostRpcPgpArmorHeadersParamsPrefer.
const (
	PostRpcPgpArmorHeadersParamsPreferParamsSingleObject PostRpcPgpArmorHeadersParamsPrefer = "params=single-object"
)

// Defines values for PostRpcPgpKeyIdParamsPrefer.
const (
	ParamsSingleObject PostRpcPgpKeyIdParamsPrefer = "params=single-object"
)

// PreferParams defines model for preferParams.
type PreferParams string

// Args defines model for Args.
type Args struct {
	Empty string `json:""`
}

// Args2 defines model for Args2.
type Args2 struct {
	Empty string `json:""`
}

// GetRpcArmorParams defines parameters for GetRpcArmor.
type GetRpcArmorParams struct {
	Empty string `form:"" json:""`
}

// PostRpcArmorJSONBody defines parameters for PostRpcArmor.
type PostRpcArmorJSONBody struct {
	Empty string `json:""`
}

// PostRpcArmorApplicationVndPgrstObjectPlusJSONBody defines parameters for PostRpcArmor.
type PostRpcArmorApplicationVndPgrstObjectPlusJSONBody struct {
	Empty string `json:""`
}

// PostRpcArmorApplicationVndPgrstObjectPlusJSONNullsStrippedBody defines parameters for PostRpcArmor.
type PostRpcArmorApplicationVndPgrstObjectPlusJSONNullsStrippedBody struct {
	Empty string `json:""`
}

// PostRpcArmorParams defines parameters for PostRpcArmor.
type PostRpcArmorParams struct {
	// Prefer Preference
	Prefer *PostRpcArmorParamsPrefer `json:"Prefer,omitempty"`
}

// PostRpcArmorParamsPrefer defines parameters for PostRpcArmor.
type PostRpcArmorParamsPrefer string

// GetRpcDearmorParams defines parameters for GetRpcDearmor.
type GetRpcDearmorParams struct {
	Empty string `form:"" json:""`
}

// PostRpcDearmorJSONBody defines parameters for PostRpcDearmor.
type PostRpcDearmorJSONBody struct {
	Empty string `json:""`
}

// PostRpcDearmorApplicationVndPgrstObjectPlusJSONBody defines parameters for PostRpcDearmor.
type PostRpcDearmorApplicationVndPgrstObjectPlusJSONBody struct {
	Empty string `json:""`
}

// PostRpcDearmorApplicationVndPgrstObjectPlusJSONNullsStrippedBody defines parameters for PostRpcDearmor.
type PostRpcDearmorApplicationVndPgrstObjectPlusJSONNullsStrippedBody struct {
	Empty string `json:""`
}

// PostRpcDearmorParams defines parameters for PostRpcDearmor.
type PostRpcDearmorParams struct {
	// Prefer Preference
	Prefer *PostRpcDearmorParamsPrefer `json:"Prefer,omitempty"`
}

// PostRpcDearmorParamsPrefer defines parameters for PostRpcDearmor.
type PostRpcDearmorParamsPrefer string

// PostRpcGenRandomUuidJSONBody defines parameters for PostRpcGenRandomUuid.
type PostRpcGenRandomUuidJSONBody = map[string]interface{}

// PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONBody defines parameters for PostRpcGenRandomUuid.
type PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONBody = map[string]interface{}

// PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONNullsStrippedBody defines parameters for PostRpcGenRandomUuid.
type PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONNullsStrippedBody = map[string]interface{}

// PostRpcGenRandomUuidParams defines parameters for PostRpcGenRandomUuid.
type PostRpcGenRandomUuidParams struct {
	// Prefer Preference
	Prefer *PostRpcGenRandomUuidParamsPrefer `json:"Prefer,omitempty"`
}

// PostRpcGenRandomUuidParamsPrefer defines parameters for PostRpcGenRandomUuid.
type PostRpcGenRandomUuidParamsPrefer string

// GetRpcGenSaltParams defines parameters for GetRpcGenSalt.
type GetRpcGenSaltParams struct {
	Empty string `form:"" json:""`
}

// PostRpcGenSaltJSONBody defines parameters for PostRpcGenSalt.
type PostRpcGenSaltJSONBody struct {
	Empty string `json:""`
}

// PostRpcGenSaltApplicationVndPgrstObjectPlusJSONBody defines parameters for PostRpcGenSalt.
type PostRpcGenSaltApplicationVndPgrstObjectPlusJSONBody struct {
	Empty string `json:""`
}

// PostRpcGenSaltApplicationVndPgrstObjectPlusJSONNullsStrippedBody defines parameters for PostRpcGenSalt.
type PostRpcGenSaltApplicationVndPgrstObjectPlusJSONNullsStrippedBody struct {
	Empty string `json:""`
}

// PostRpcGenSaltParams defines parameters for PostRpcGenSalt.
type PostRpcGenSaltParams struct {
	// Prefer Preference
	Prefer *PostRpcGenSaltParamsPrefer `json:"Prefer,omitempty"`
}

// PostRpcGenSaltParamsPrefer defines parameters for PostRpcGenSalt.
type PostRpcGenSaltParamsPrefer string

// GetRpcPgpArmorHeadersParams defines parameters for GetRpcPgpArmorHeaders.
type GetRpcPgpArmorHeadersParams struct {
	Empty string `form:"" json:""`
}

// PostRpcPgpArmorHeadersJSONBody defines parameters for PostRpcPgpArmorHeaders.
type PostRpcPgpArmorHeadersJSONBody struct {
	Empty string `json:""`
}

// PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONBody defines parameters for PostRpcPgpArmorHeaders.
type PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONBody struct {
	Empty string `json:""`
}

// PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONNullsStrippedBody defines parameters for PostRpcPgpArmorHeaders.
type PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONNullsStrippedBody struct {
	Empty string `json:""`
}

// PostRpcPgpArmorHeadersParams defines parameters for PostRpcPgpArmorHeaders.
type PostRpcPgpArmorHeadersParams struct {
	// Prefer Preference
	Prefer *PostRpcPgpArmorHeadersParamsPrefer `json:"Prefer,omitempty"`
}

// PostRpcPgpArmorHeadersParamsPrefer defines parameters for PostRpcPgpArmorHeaders.
type PostRpcPgpArmorHeadersParamsPrefer string

// GetRpcPgpKeyIdParams defines parameters for GetRpcPgpKeyId.
type GetRpcPgpKeyIdParams struct {
	Empty string `form:"" json:""`
}

// PostRpcPgpKeyIdJSONBody defines parameters for PostRpcPgpKeyId.
type PostRpcPgpKeyIdJSONBody struct {
	Empty string `json:""`
}

// PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONBody defines parameters for PostRpcPgpKeyId.
type PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONBody struct {
	Empty string `json:""`
}

// PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONNullsStrippedBody defines parameters for PostRpcPgpKeyId.
type PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONNullsStrippedBody struct {
	Empty string `json:""`
}

// PostRpcPgpKeyIdParams defines parameters for PostRpcPgpKeyId.
type PostRpcPgpKeyIdParams struct {
	// Prefer Preference
	Prefer *PostRpcPgpKeyIdParamsPrefer `json:"Prefer,omitempty"`
}

// PostRpcPgpKeyIdParamsPrefer defines parameters for PostRpcPgpKeyId.
type PostRpcPgpKeyIdParamsPrefer string

// PostRpcArmorJSONRequestBody defines body for PostRpcArmor for application/json ContentType.
type PostRpcArmorJSONRequestBody PostRpcArmorJSONBody

// PostRpcArmorApplicationVndPgrstObjectPlusJSONRequestBody defines body for PostRpcArmor for application/vnd.pgrst.object+json ContentType.
type PostRpcArmorApplicationVndPgrstObjectPlusJSONRequestBody PostRpcArmorApplicationVndPgrstObjectPlusJSONBody

// PostRpcArmorApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody defines body for PostRpcArmor for application/vnd.pgrst.object+json;nulls=stripped ContentType.
type PostRpcArmorApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody PostRpcArmorApplicationVndPgrstObjectPlusJSONNullsStrippedBody

// PostRpcDearmorJSONRequestBody defines body for PostRpcDearmor for application/json ContentType.
type PostRpcDearmorJSONRequestBody PostRpcDearmorJSONBody

// PostRpcDearmorApplicationVndPgrstObjectPlusJSONRequestBody defines body for PostRpcDearmor for application/vnd.pgrst.object+json ContentType.
type PostRpcDearmorApplicationVndPgrstObjectPlusJSONRequestBody PostRpcDearmorApplicationVndPgrstObjectPlusJSONBody

// PostRpcDearmorApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody defines body for PostRpcDearmor for application/vnd.pgrst.object+json;nulls=stripped ContentType.
type PostRpcDearmorApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody PostRpcDearmorApplicationVndPgrstObjectPlusJSONNullsStrippedBody

// PostRpcGenRandomUuidJSONRequestBody defines body for PostRpcGenRandomUuid for application/json ContentType.
type PostRpcGenRandomUuidJSONRequestBody = PostRpcGenRandomUuidJSONBody

// PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONRequestBody defines body for PostRpcGenRandomUuid for application/vnd.pgrst.object+json ContentType.
type PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONRequestBody = PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONBody

// PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody defines body for PostRpcGenRandomUuid for application/vnd.pgrst.object+json;nulls=stripped ContentType.
type PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody = PostRpcGenRandomUuidApplicationVndPgrstObjectPlusJSONNullsStrippedBody

// PostRpcGenSaltJSONRequestBody defines body for PostRpcGenSalt for application/json ContentType.
type PostRpcGenSaltJSONRequestBody PostRpcGenSaltJSONBody

// PostRpcGenSaltApplicationVndPgrstObjectPlusJSONRequestBody defines body for PostRpcGenSalt for application/vnd.pgrst.object+json ContentType.
type PostRpcGenSaltApplicationVndPgrstObjectPlusJSONRequestBody PostRpcGenSaltApplicationVndPgrstObjectPlusJSONBody

// PostRpcGenSaltApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody defines body for PostRpcGenSalt for application/vnd.pgrst.object+json;nulls=stripped ContentType.
type PostRpcGenSaltApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody PostRpcGenSaltApplicationVndPgrstObjectPlusJSONNullsStrippedBody

// PostRpcPgpArmorHeadersJSONRequestBody defines body for PostRpcPgpArmorHeaders for application/json ContentType.
type PostRpcPgpArmorHeadersJSONRequestBody PostRpcPgpArmorHeadersJSONBody

// PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONRequestBody defines body for PostRpcPgpArmorHeaders for application/vnd.pgrst.object+json ContentType.
type PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONRequestBody PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONBody

// PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody defines body for PostRpcPgpArmorHeaders for application/vnd.pgrst.object+json;nulls=stripped ContentType.
type PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody PostRpcPgpArmorHeadersApplicationVndPgrstObjectPlusJSONNullsStrippedBody

// PostRpcPgpKeyIdJSONRequestBody defines body for PostRpcPgpKeyId for application/json ContentType.
type PostRpcPgpKeyIdJSONRequestBody PostRpcPgpKeyIdJSONBody

// PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONRequestBody defines body for PostRpcPgpKeyId for application/vnd.pgrst.object+json ContentType.
type PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONRequestBody PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONBody

// PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody defines body for PostRpcPgpKeyId for application/vnd.pgrst.object+json;nulls=stripped ContentType.
type PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONNullsStrippedRequestBody PostRpcPgpKeyIdApplicationVndPgrstObjectPlusJSONNullsStrippedBody
