// To generate the Go code from this proto file, run: `make proto_generate`
// See `proto.mk` for more details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: path/gateway.proto

package observation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestType captures the origin of the request.
// As of PR #72, it is one of:
//  1. Organic: a real user sent a service request to a PATH instance
//  2. Synthetic: internal infrastructure generated the service request for simulation and data purposes.
type RequestType int32

const (
	RequestType_REQUEST_TYPE_UNSPECIFIED RequestType = 0
	RequestType_REQUEST_TYPE_ORGANIC     RequestType = 1 // Service request sent by a user.
	RequestType_REQUEST_TYPE_SYNTHETIC   RequestType = 2 // Service request sent by the endpoint hydrator: see gateway/hydrator.go.
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REQUEST_TYPE_UNSPECIFIED",
		1: "REQUEST_TYPE_ORGANIC",
		2: "REQUEST_TYPE_SYNTHETIC",
	}
	RequestType_value = map[string]int32{
		"REQUEST_TYPE_UNSPECIFIED": 0,
		"REQUEST_TYPE_ORGANIC":     1,
		"REQUEST_TYPE_SYNTHETIC":   2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_path_gateway_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_path_gateway_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_path_gateway_proto_rawDescGZIP(), []int{0}
}

// GatewayObservations is the set of observations on a service request, made from the perspective of a gateway.
// Examples include the geographic region of the request, the request type, etc.
type GatewayObservations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_auth stores any fields related to the identification/authentication of the request.
	RequestAuth *RequestAuth `protobuf:"bytes,1,opt,name=request_auth,json=requestAuth,proto3" json:"request_auth,omitempty"`
	// Specifies the request type.
	// For example, wWhether the request was sent by a user or synthetically generated (e.g. by the endpoint hydrator).
	RequestType RequestType `protobuf:"varint,2,opt,name=request_type,json=requestType,proto3,enum=path.RequestType" json:"request_type,omitempty"`
	// service_id is the identifier specified via custom HTTP header.
	// As of PR #72, this can only be specified through a custom header on the HTTP request, extracted in `request/parser.go`.
	ServiceId string `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// received_time is when the request was initially received
	ReceivedTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=received_time,json=receivedTime,proto3" json:"received_time,omitempty"`
	// completed_time is when request processing finished and response was returned
	CompletedTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_time,json=completedTime,proto3" json:"completed_time,omitempty"`
	// response_size is the size in bytes of the response payload
	ResponseSize  uint64 `protobuf:"varint,6,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayObservations) Reset() {
	*x = GatewayObservations{}
	mi := &file_path_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayObservations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayObservations) ProtoMessage() {}

func (x *GatewayObservations) ProtoReflect() protoreflect.Message {
	mi := &file_path_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayObservations.ProtoReflect.Descriptor instead.
func (*GatewayObservations) Descriptor() ([]byte, []int) {
	return file_path_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayObservations) GetRequestAuth() *RequestAuth {
	if x != nil {
		return x.RequestAuth
	}
	return nil
}

func (x *GatewayObservations) GetRequestType() RequestType {
	if x != nil {
		return x.RequestType
	}
	return RequestType_REQUEST_TYPE_UNSPECIFIED
}

func (x *GatewayObservations) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GatewayObservations) GetReceivedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedTime
	}
	return nil
}

func (x *GatewayObservations) GetCompletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedTime
	}
	return nil
}

func (x *GatewayObservations) GetResponseSize() uint64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

var File_path_gateway_proto protoreflect.FileDescriptor

const file_path_gateway_proto_rawDesc = "" +
	"\n" +
	"\x12path/gateway.proto\x12\x04path\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fpath/auth.proto\"\xc9\x02\n" +
	"\x13GatewayObservations\x124\n" +
	"\frequest_auth\x18\x01 \x01(\v2\x11.path.RequestAuthR\vrequestAuth\x124\n" +
	"\frequest_type\x18\x02 \x01(\x0e2\x11.path.RequestTypeR\vrequestType\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12?\n" +
	"\rreceived_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\freceivedTime\x12A\n" +
	"\x0ecompleted_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rcompletedTime\x12#\n" +
	"\rresponse_size\x18\x06 \x01(\x04R\fresponseSize*a\n" +
	"\vRequestType\x12\x1c\n" +
	"\x18REQUEST_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REQUEST_TYPE_ORGANIC\x10\x01\x12\x1a\n" +
	"\x16REQUEST_TYPE_SYNTHETIC\x10\x02B,Z*github.com/buildwithgrove/path/observationb\x06proto3"

var (
	file_path_gateway_proto_rawDescOnce sync.Once
	file_path_gateway_proto_rawDescData []byte
)

func file_path_gateway_proto_rawDescGZIP() []byte {
	file_path_gateway_proto_rawDescOnce.Do(func() {
		file_path_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_path_gateway_proto_rawDesc), len(file_path_gateway_proto_rawDesc)))
	})
	return file_path_gateway_proto_rawDescData
}

var file_path_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_path_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_path_gateway_proto_goTypes = []any{
	(RequestType)(0),              // 0: path.RequestType
	(*GatewayObservations)(nil),   // 1: path.GatewayObservations
	(*RequestAuth)(nil),           // 2: path.RequestAuth
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_path_gateway_proto_depIdxs = []int32{
	2, // 0: path.GatewayObservations.request_auth:type_name -> path.RequestAuth
	0, // 1: path.GatewayObservations.request_type:type_name -> path.RequestType
	3, // 2: path.GatewayObservations.received_time:type_name -> google.protobuf.Timestamp
	3, // 3: path.GatewayObservations.completed_time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_path_gateway_proto_init() }
func file_path_gateway_proto_init() {
	if File_path_gateway_proto != nil {
		return
	}
	file_path_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_path_gateway_proto_rawDesc), len(file_path_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_gateway_proto_goTypes,
		DependencyIndexes: file_path_gateway_proto_depIdxs,
		EnumInfos:         file_path_gateway_proto_enumTypes,
		MessageInfos:      file_path_gateway_proto_msgTypes,
	}.Build()
	File_path_gateway_proto = out.File
	file_path_gateway_proto_goTypes = nil
	file_path_gateway_proto_depIdxs = nil
}
