# This is an example config file to run a local development environment using the Shannon protocol as a relayer.
#
# Run `make config_shannon_localnet` to use it and update `protocol.shannon_config.full_node_config.gateway_private_key`
# 
# DEV_NOTE: only the `gateway_private_key` value should be updated.
shannon_config:
  full_node_config:
    # DO NOT change rpc_url unless you know what you're doing
    rpc_url: https://shannon-testnet-grove-seed-rpc.poktroll.com 
    grpc_config:
      # do not change host_port
      host_port: shannon-testnet-grove-seed-grpc.poktroll.com:443 
    # NOTE: gateway_private_key must be replaced with the correct gateway private key secret
    gateway_private_key: cf09805c952fa999e9a63a9f434147b0a5abfd10f268879694c6b5a70e1ae177 
    gateway_address: pokt1up7zlytnmvlsuxzpzvlrta95347w322adsxslw 
    delegated_app_addresses: 
      - pokt1gsufws4c5dhemd0z3njfh859xl0624xyyw5m87 
services:
  "0021":
    alias: "eth-mainnet"
hydrator_config:
  service_ids:
    - 0021
