/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.2 (a4e00ff)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface RpcGenRandomUuidPostRequest {
    body: object;
    prefer?: RpcGenRandomUuidPostPreferEnum;
}

/**
 * 
 */
export class RpcGenRandomUuidApi extends runtime.BaseAPI {

    /**
     */
    async rpcGenRandomUuidGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rpc/gen_random_uuid`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async rpcGenRandomUuidGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rpcGenRandomUuidGetRaw(initOverrides);
    }

    /**
     */
    async rpcGenRandomUuidPostRaw(requestParameters: RpcGenRandomUuidPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling rpcGenRandomUuidPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['prefer'] != null) {
            headerParameters['Prefer'] = String(requestParameters['prefer']);
        }


        let urlPath = `/rpc/gen_random_uuid`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async rpcGenRandomUuidPost(requestParameters: RpcGenRandomUuidPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rpcGenRandomUuidPostRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const RpcGenRandomUuidPostPreferEnum = {
    ParamssingleObject: 'params=single-object'
} as const;
export type RpcGenRandomUuidPostPreferEnum = typeof RpcGenRandomUuidPostPreferEnum[keyof typeof RpcGenRandomUuidPostPreferEnum];
