// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: path/protocol/observations.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Observations aggregates protocol-level observations collected during service request processing.
type Observations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Height of the blockchain block when processing the service request through a relay
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Shannon protocol-specific observations
	Shannon       *ShannonObservationsList `protobuf:"bytes,2,opt,name=shannon,proto3" json:"shannon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observations) Reset() {
	*x = Observations{}
	mi := &file_path_protocol_observations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observations) ProtoMessage() {}

func (x *Observations) ProtoReflect() protoreflect.Message {
	mi := &file_path_protocol_observations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observations.ProtoReflect.Descriptor instead.
func (*Observations) Descriptor() ([]byte, []int) {
	return file_path_protocol_observations_proto_rawDescGZIP(), []int{0}
}

func (x *Observations) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Observations) GetShannon() *ShannonObservationsList {
	if x != nil {
		return x.Shannon
	}
	return nil
}

var File_path_protocol_observations_proto protoreflect.FileDescriptor

const file_path_protocol_observations_proto_rawDesc = "" +
	"\n" +
	" path/protocol/observations.proto\x12\rpath.protocol\x1a\x1bpath/protocol/shannon.proto\"s\n" +
	"\fObservations\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12@\n" +
	"\ashannon\x18\x02 \x01(\v2&.path.protocol.ShannonObservationsListR\ashannonB5Z3github.com/buildwithgrove/path/observation/protocolb\x06proto3"

var (
	file_path_protocol_observations_proto_rawDescOnce sync.Once
	file_path_protocol_observations_proto_rawDescData []byte
)

func file_path_protocol_observations_proto_rawDescGZIP() []byte {
	file_path_protocol_observations_proto_rawDescOnce.Do(func() {
		file_path_protocol_observations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_path_protocol_observations_proto_rawDesc), len(file_path_protocol_observations_proto_rawDesc)))
	})
	return file_path_protocol_observations_proto_rawDescData
}

var file_path_protocol_observations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_path_protocol_observations_proto_goTypes = []any{
	(*Observations)(nil),            // 0: path.protocol.Observations
	(*ShannonObservationsList)(nil), // 1: path.protocol.ShannonObservationsList
}
var file_path_protocol_observations_proto_depIdxs = []int32{
	1, // 0: path.protocol.Observations.shannon:type_name -> path.protocol.ShannonObservationsList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_path_protocol_observations_proto_init() }
func file_path_protocol_observations_proto_init() {
	if File_path_protocol_observations_proto != nil {
		return
	}
	file_path_protocol_shannon_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_path_protocol_observations_proto_rawDesc), len(file_path_protocol_observations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_protocol_observations_proto_goTypes,
		DependencyIndexes: file_path_protocol_observations_proto_depIdxs,
		MessageInfos:      file_path_protocol_observations_proto_msgTypes,
	}.Build()
	File_path_protocol_observations_proto = out.File
	file_path_protocol_observations_proto_goTypes = nil
	file_path_protocol_observations_proto_depIdxs = nil
}
