package db

import (
	"context"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/pokt-network/poktroll/pkg/polylog/polyzero"
	mock "github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"

	"github.com/buildwithgrove/path/user"
)

func Test_GetUserApp(t *testing.T) {
	tests := []struct {
		name       string
		userAppID  user.UserAppID
		mockReturn map[user.UserAppID]user.UserApp
		expected   user.UserApp
		found      bool
	}{
		{
			name:       "should return user app when found",
			userAppID:  "user_app_1",
			mockReturn: getTestUserApps(),
			expected:   getTestUserApps()["user_app_1"],
			found:      true,
		},
		{
			name:       "should return different user app when found",
			userAppID:  "user_app_2",
			mockReturn: getTestUserApps(),
			expected:   getTestUserApps()["user_app_2"],
			found:      true,
		},
		{
			name:       "should return false when user app not found",
			userAppID:  "user_app_3",
			mockReturn: getTestUserApps(),
			expected:   user.UserApp{},
			found:      false,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := require.New(t)
			cache, err := newTestCache(t, test.mockReturn)
			c.NoError(err)

			userApp, found := cache.GetUserApp(context.Background(), test.userAppID)
			c.Equal(test.found, found)
			c.Equal(test.expected, userApp)
		})
	}
}

func Test_cacheRefreshHandler(t *testing.T) {
	tests := []struct {
		name       string
		mockReturn map[user.UserAppID]user.UserApp
		expected   map[user.UserAppID]user.UserApp
	}{
		{
			name:       "should refresh cache with new data",
			mockReturn: map[user.UserAppID]user.UserApp{"user_app_1": {ID: "user_app_1"}},
			expected:   map[user.UserAppID]user.UserApp{"user_app_1": {ID: "user_app_1"}},
		},
		{
			name:       "should handle empty cache refresh",
			mockReturn: map[user.UserAppID]user.UserApp{},
			expected:   map[user.UserAppID]user.UserApp{},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := require.New(t)
			cache, err := newTestCache(t, test.mockReturn)
			c.NoError(err)

			cache.cacheRefreshInterval = time.Millisecond * 10

			go cache.cacheRefreshHandler(context.Background())

			time.Sleep(time.Millisecond * 20)

			c.Equal(test.expected, cache.userApps)
		})
	}
}

func Test_setCache(t *testing.T) {
	tests := []struct {
		name       string
		mockReturn map[user.UserAppID]user.UserApp
		expected   map[user.UserAppID]user.UserApp
	}{
		{
			name:       "should set cache with user apps",
			mockReturn: map[user.UserAppID]user.UserApp{"user_app_1": {ID: "user_app_1"}},
			expected:   map[user.UserAppID]user.UserApp{"user_app_1": {ID: "user_app_1"}},
		},
		{
			name:       "should handle empty user apps",
			mockReturn: map[user.UserAppID]user.UserApp{},
			expected:   map[user.UserAppID]user.UserApp{},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := require.New(t)
			cache, err := newTestCache(t, test.mockReturn)
			c.NoError(err)

			err = cache.setCache(context.Background())
			c.NoError(err)
			c.Equal(test.expected, cache.userApps)
		})
	}
}

func newTestCache(t *testing.T, userApps map[user.UserAppID]user.UserApp) (*cache, error) {
	mockDb := newMockDbDriver(t)

	cache := &cache{
		userApps:             make(map[user.UserAppID]user.UserApp),
		db:                   mockDb,
		cacheRefreshInterval: time.Minute,
		mu:                   sync.RWMutex{},
		logger:               polyzero.NewLogger(),
	}

	mockDb.On("GetUserApps", mock.Anything).Return(userApps, nil)

	if err := cache.setCache(context.Background()); err != nil {
		return nil, fmt.Errorf("failed to set cache: %w", err)
	}

	go cache.cacheRefreshHandler(context.Background())

	return cache, nil
}

func getTestUserApps() map[user.UserAppID]user.UserApp {
	return map[user.UserAppID]user.UserApp{
		"user_app_1": {
			ID:                "user_app_1",
			AccountID:         "account_1",
			PlanType:          "PLAN_FREE",
			SecretKey:         "secret_1",
			SecretKeyRequired: true,
			ThroughputLimit:   30,
			Allowlists: map[user.AllowlistType]map[string]struct{}{
				user.AllowlistTypeOrigins:   {"origin_1": {}},
				user.AllowlistTypeContracts: {"contract_1": {}},
			},
		},
		"user_app_2": {
			ID:                "user_app_2",
			AccountID:         "account_2",
			PlanType:          "PLAN_UNLIMITED",
			SecretKey:         "secret_2",
			SecretKeyRequired: true,
			ThroughputLimit:   0,
			Allowlists: map[user.AllowlistType]map[string]struct{}{
				user.AllowlistTypeOrigins:   {"origin_2": {}},
				user.AllowlistTypeContracts: {"contract_2": {}},
			},
		},
	}
}

// Code below generated by mockery v2.41.0. DO NOT EDIT.

// mockDbDriver is an autogenerated mock type for the dbDriver type
type mockDbDriver struct {
	mock.Mock
}

// GetUserApps provides a mock function with given fields: ctx
func (_m *mockDbDriver) GetUserApps(ctx context.Context) (map[user.UserAppID]user.UserApp, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserApps")
	}

	var r0 map[user.UserAppID]user.UserApp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[user.UserAppID]user.UserApp, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[user.UserAppID]user.UserApp); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(map[user.UserAppID]user.UserApp)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockDbDriver creates a new instance of mockDbDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDbDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDbDriver {
	mock := &mockDbDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
