{
 "title": "Service Requests",
 "tags": [
  "path",
  "requests"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Received Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service_id) (path_requests_total{container=\"path\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Response Size Histogram", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 } },
  { "title": "QoS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "EVM QoS Service Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(request_method) (path_evm_requests_total{container=\"path\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM QoS Requests Success by Chain ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(chain_id) (path_evm_requests_total{container=\"path\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}