# yaml-language-server: $schema=https://raw.githubusercontent.com/buildwithgrove/path/refs/heads/main/config/config.schema.yaml
# The above schema URL may be used to validate this file using the `yaml-language-server` VSCode extension.
# See: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

shannon_config:
  full_node_config:
    rpc_url: https://example_full_node_rpc_url.your_domain # replace with your full node rpc url
    grpc_config:
      host_port: example_fullnode_grpc.your_domain:443 # replace with your full node grpc host:port
    lazy_mode: false # set to true to disable PATH caching mechanism
  gateway_config:
    gateway_mode: centralized # replace with your gateway mode centralized|delegated|trusted
    gateway_address: pokt1710ed9a8d0986d808e607c5815cc5a13f15dba # replace with your gateway address
    gateway_private_key_hex: d5fcbfb894059a21e914a2d6bf1508319ce2b1b8878f15aa0c1cdf883feb018d # replace with your gateway private key
    # Not applicable for delegated gateway mode
    owned_apps_private_keys_hex: # replace with delegated app addresses
      - e5fcbfb894059a21e914a2d6bf1508319ce2b1b8878f15aa0c1cdf883feb018d

services:
  "F00C":
    alias: "eth"
