# yaml-language-server: $schema=../config/config.schema.yaml

shannon_config:
  full_node_config:
    rpc_url: https://example_full_node_rpc_url.your_domain # replace with your full node rpc url
    grpc_config:
      host_port: example_fullnode_grpc.your_domain:443 # replace with your full node grpc host:port
    lazy_mode: false # set to true to disable PATH caching mechanism
  gateway_config:
    gateway_mode: centralized # replace with your gateway mode centralized|delegated|trusted
    gateway_address: pokt10f3838db8c7830f172329442ac0be0a6340804 # replace with your gateway address
    gateway_private_key_hex: 4c43d5142b5217b91b3d8659ad691657cde1050f9260fb0a722feabe329b536a # replace with your gateway private key
    # Not applicable for delegated gateway mode
    owned_apps_private_keys_hex: # replace with delegated app addresses
      - db9cab4a9e26eaf6357b3345c3e59e4b0150925bfe660626ca5761d2e65c97bd

services:
  "F00C":
    alias: "eth"
