shannon_config:
  full_node_config:
    rpc_url: https://example_full_node_rpc_url.your_domain # replace with your full node rpc url
    grpc_config:
      host_port: example_fullnode_grpc.your_domain:443 # replace with your full node grpc host/port
    gateway_address: "example_gateway_address_pokt1710ed9a8d0986d8" # replace with your gateway address
    gateway_private_key: "example_gateway_private_key_52734539d033e35c6e6d1ce5ad96bcacb911" # replace with your gateway private key
    delegated_app_addresses: # replace with delegated app addresses
      - "example_delegated_app_address_pokt1a3b8ef9b"

services:
  "0021":
    alias: "eth-mainnet"
