# ---- GUARD Global settings ----
global:
  # Set `localhost` for local development.
  domain: localhost
  # namespace is the k8s namespace that both Envoy Gateway and the PATH service are deployed to.
  namespace: path-local

# ---- GUARD configuration ----
guard:
  # Set the services that are allowed to access the PATH service.
  # For example, if running PATH in Shannon mode, you would set:
  services:
    - serviceId: anvil
