/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.2 (a4e00ff)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Supported blockchain networks (Pocket mainnet, testnet, etc.)
 * @export
 * @interface Networks
 */
export interface Networks {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * @type {string}
     * @memberof Networks
     */
    networkId: string;
}

/**
 * Check if a given object implements the Networks interface.
 */
export function instanceOfNetworks(value: object): value is Networks {
    if (!('networkId' in value) || value['networkId'] === undefined) return false;
    return true;
}

export function NetworksFromJSON(json: any): Networks {
    return NetworksFromJSONTyped(json, false);
}

export function NetworksFromJSONTyped(json: any, ignoreDiscriminator: boolean): Networks {
    if (json == null) {
        return json;
    }
    return {
        
        'networkId': json['network_id'],
    };
}

export function NetworksToJSON(json: any): Networks {
    return NetworksToJSONTyped(json, false);
}

export function NetworksToJSONTyped(value?: Networks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network_id': value['networkId'],
    };
}

