/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.2 (a4e00ff)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Account data for portal-workers billing operations with owner email. Filter using WHERE portal_plan_type = 'PLAN_UNLIMITED' AND billing_type = 'stripe'
 * @export
 * @interface PortalWorkersAccountData
 */
export interface PortalWorkersAccountData {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * @type {string}
     * @memberof PortalWorkersAccountData
     */
    portalAccountId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortalWorkersAccountData
     */
    userAccountName?: string;
    /**
     * Note:
     * This is a Foreign Key to `portal_plans.portal_plan_type`.<fk table='portal_plans' column='portal_plan_type'/>
     * @type {string}
     * @memberof PortalWorkersAccountData
     */
    portalPlanType?: string;
    /**
     * 
     * @type {string}
     * @memberof PortalWorkersAccountData
     */
    billingType?: string;
    /**
     * 
     * @type {number}
     * @memberof PortalWorkersAccountData
     */
    portalAccountUserLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof PortalWorkersAccountData
     */
    gcpEntitlementId?: string;
    /**
     * 
     * @type {string}
     * @memberof PortalWorkersAccountData
     */
    ownerEmail?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * @type {string}
     * @memberof PortalWorkersAccountData
     */
    ownerUserId?: string;
}

/**
 * Check if a given object implements the PortalWorkersAccountData interface.
 */
export function instanceOfPortalWorkersAccountData(value: object): value is PortalWorkersAccountData {
    return true;
}

export function PortalWorkersAccountDataFromJSON(json: any): PortalWorkersAccountData {
    return PortalWorkersAccountDataFromJSONTyped(json, false);
}

export function PortalWorkersAccountDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortalWorkersAccountData {
    if (json == null) {
        return json;
    }
    return {
        
        'portalAccountId': json['portal_account_id'] == null ? undefined : json['portal_account_id'],
        'userAccountName': json['user_account_name'] == null ? undefined : json['user_account_name'],
        'portalPlanType': json['portal_plan_type'] == null ? undefined : json['portal_plan_type'],
        'billingType': json['billing_type'] == null ? undefined : json['billing_type'],
        'portalAccountUserLimit': json['portal_account_user_limit'] == null ? undefined : json['portal_account_user_limit'],
        'gcpEntitlementId': json['gcp_entitlement_id'] == null ? undefined : json['gcp_entitlement_id'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
    };
}

export function PortalWorkersAccountDataToJSON(json: any): PortalWorkersAccountData {
    return PortalWorkersAccountDataToJSONTyped(json, false);
}

export function PortalWorkersAccountDataToJSONTyped(value?: PortalWorkersAccountData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portal_account_id': value['portalAccountId'],
        'user_account_name': value['userAccountName'],
        'portal_plan_type': value['portalPlanType'],
        'billing_type': value['billingType'],
        'portal_account_user_limit': value['portalAccountUserLimit'],
        'gcp_entitlement_id': value['gcpEntitlementId'],
        'owner_email': value['ownerEmail'],
        'owner_user_id': value['ownerUserId'],
    };
}

