/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.2 (a4e00ff)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User access controls for specific applications
 * @export
 * @interface PortalApplicationRbac
 */
export interface PortalApplicationRbac {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * @type {number}
     * @memberof PortalApplicationRbac
     */
    id: number;
    /**
     * Note:
     * This is a Foreign Key to `portal_applications.portal_application_id`.<fk table='portal_applications' column='portal_application_id'/>
     * @type {string}
     * @memberof PortalApplicationRbac
     */
    portalApplicationId: string;
    /**
     * Note:
     * This is a Foreign Key to `portal_users.portal_user_id`.<fk table='portal_users' column='portal_user_id'/>
     * @type {string}
     * @memberof PortalApplicationRbac
     */
    portalUserId: string;
    /**
     * 
     * @type {string}
     * @memberof PortalApplicationRbac
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PortalApplicationRbac
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the PortalApplicationRbac interface.
 */
export function instanceOfPortalApplicationRbac(value: object): value is PortalApplicationRbac {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('portalApplicationId' in value) || value['portalApplicationId'] === undefined) return false;
    if (!('portalUserId' in value) || value['portalUserId'] === undefined) return false;
    return true;
}

export function PortalApplicationRbacFromJSON(json: any): PortalApplicationRbac {
    return PortalApplicationRbacFromJSONTyped(json, false);
}

export function PortalApplicationRbacFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortalApplicationRbac {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'portalApplicationId': json['portal_application_id'],
        'portalUserId': json['portal_user_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function PortalApplicationRbacToJSON(json: any): PortalApplicationRbac {
    return PortalApplicationRbacToJSONTyped(json, false);
}

export function PortalApplicationRbacToJSONTyped(value?: PortalApplicationRbac | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'portal_application_id': value['portalApplicationId'],
        'portal_user_id': value['portalUserId'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

