# yaml-language-server: $schema=../../config/config.schema.yaml

shannon_config:
  full_node_config:
    rpc_url: https://testnet-validated-validator-rpc.poktroll.com # replace with your full node rpc url
    grpc_config:
      host_port: testnet-validated-validator-grpc.poktroll.com:443 # replace with your full node grpc host:port
    lazy_mode: false # set to true to disable PATH caching mechanism
  gateway_config:
    gateway_mode: "centralized"
    # NOTE: gateway_private_key_hex must be replaced with the correct gateway private key secret
    gateway_private_key_hex: cf09805c952fa999e9a63a9f434147b0a5abfd10f268879694c6b5a70e1ae177  # ATTENTION: this is a place-holder for a sensitive data item which should never be shared outside your organization.
    # do not change gateway_address
    gateway_address: pokt1up7zlytnmvlsuxzpzvlrta95347w322adsxslw 
    owned_apps_private_keys_hex:
      # NOTE: the application private key must be replaced with the correct application private key secret
      - cf09805c952fa999e9a63a9f434147b0a5abfd10f268879694c6b5a70e1ae177

# services is required. At least one service must be configured with a valid id.
# All fields are optional but the id is required.
services:
  # gatewaye2e is the ID for the service used by the Shannon E2E tests
  "gatewaye2e":
    # test-service is the alias for the service used by the Shannon E2E tests
    alias: "test-service"
  "0021":
    alias: "eth"
  "0001": {} # Example of a service with no additional configuration

# Enable endpoint hydrator to run QoS checks against endpoints of service F00C
hydrator_config:
  service_ids:
    - "0021"
