# yaml-language-server: $schema=https://raw.githubusercontent.com/buildwithgrove/path/refs/heads/main/config/config.schema.yaml
#
# The above schema URL may be used to validate this file using the `yaml-language-server` VSCode extension.
# See: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
#
# Use the following if you need it to point to the local schema file:
# yaml-language-server: $schema=../../../config/config.schema.yaml

###############################################
### Example Morse Configuration YAML Format ###
###############################################

# DEV_NOTE: The keys in this file are just random hex codes to bypass schema validation.

morse_config:
  full_node_config:
    # DO NOT change rpc_url unless you know what you're doing
    url: "https://pocket-rpc.liquify.com"

    # README: relay_signing_key MUST BE replaced with your personal gateway private key secret
    # ATTENTION: this is a place-holder for a sensitive data item which should never be shared outside your organization.
    relay_signing_key: "40af4e7e1b311c76a573610fe115cd2adf1eeade709cd77ca31ad4472509d38840af4e7e1b311c76a573610fe115cd2adf1eeade709cd77ca31ad4472509d388"

    http_config:
      retries: 3
      timeout: "5000ms"

  # README: signed_aats MUST BE replaced with the AATs of your Morse applications.
  # All signed AAT fields are place-holders for sensitive data items which should never be shared outside your organization.
  # See the following link for more details:
  # https://docs.pokt.network/gateways/host-a-gateway/relay-process#what-are-aats
  signed_aats:
    "40af4e7e1b311c76a573610fe115cd2adf1eeade":
      client_public_key: "40af4e7e1b311c76a573610fe115cd2adf1eeade709cd77ca31ad4472509d388"
      application_public_key: "40af4e7e1b311c76a573610fe115cd2adf1eeade709cd77ca31ad4472509d388"
      application_signature: "40af4e7e1b311c76a573610fe115cd2adf1eeade709cd77ca31ad4472509d38840af4e7e1b311c76a573610fe115cd2adf1eeade709cd77ca31ad4472509d388"

# Enable endpoint hydrator to run QoS checks against endpoints of service F00C
hydrator_config:
  service_ids:
    - "F00C"

# This configuration is loaded by the Go Auth Server only.
# See the file in `envoy/auth_server/config/config.go` for more details.
auth_server_config:
  # [REQUIRED] The host and port for the remote gRPC server connection
  # that provides the GatewayEndpoint data for the auth server.
  # Example: "localhost:50051" or "auth-server.buildwithgrove.com:443"
  grpc_host_port: path-auth-data-server:50051

  # [OPTIONAL] Whether to use insecure credentials for the gRPC connection.
  # Default is "false" if not set.
  grpc_use_insecure_credentials: true

  # [OPTIONAL] The type of extractor to use for the endpoint ID.
  # Options are "url_path" or "header".
  # Default is "url_path" if not set.
  endpoint_id_extractor_type: url_path

# Optional logger configuration
logger_config:
  # Valid values are: debug, info, warn, error
  # Defaults to info if not specified
  level: "info"
