apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz
  template:
    metadata:
      labels:
        app: ext-authz
    spec:
      containers:
        - name: ext-authz
          image: ext-authz:latest
          volumeMounts:
            - name: path-config-local
              mountPath: /app/config/.config.yaml
              subPath: .config.yaml
          ports:
            - containerPort: 50051
      volumes:
        - name: path-config-local
          secret:
            secretName: path-config-local
---
apiVersion: v1
kind: Service
metadata:
  name: ext-authz
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: ext-authz
  type: ClusterIP
