apiVersion: apps/v1
kind: Deployment
metadata:
  name: path-auth-data-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: path-auth-data-server
  template:
    metadata:
      labels:
        app: path-auth-data-server
    spec:
      containers:
        - name: path-auth-data-server
          image: ghcr.io/buildwithgrove/path-auth-data-server:latest
          env:
            # IMPORTANT: Exactly one of the following variables below must be set:
            # - YAML_FILEPATH
            # - POSTGRES_CONNECTION_STRING
            # An error will be thrown if neither or both are set.
            - name: YAML_FILEPATH
              # The .gateway-endpoints.yaml file is mounted by Tilt from ./local/path/envoy/.gateway-endpoints.yaml
              value: ".gateway-endpoints.yaml"
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: gateway-endpoints
              mountPath: /app/.gateway-endpoints.yaml
              subPath: .gateway-endpoints.yaml
      volumes:
        - name: gateway-endpoints
          configMap:
            name: gateway-endpoints
---
apiVersion: v1
kind: Service
metadata:
  name: path-auth-data-server
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: path-auth-data-server
  type: ClusterIP
