global:
  imagePullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: "path-sa"

path:
  mountSecrets:
    - name: path-config-local
      mountPath: /app/config/.config.yaml
      subPath: .config.yaml
      items:
        - key: .config.yaml
          path: .config.yaml

  replicas: 1
  resources:
    limits:
      memory: 2G
      cpu: 4
    requests:
      cpu: 1.8
      memory: 800Mi
  ports:
    - name: http
      port: 3000
      protocol: TCP
      service:
        type: ClusterIP

  # The PATH services uses the `/healthz` endpoint to check if the service is ready,
  # which uses the response from the QoS service to determine whether to send a 
  # 503 (Service Unavailable) or 200 (OK) status code.
  #
  # When using PATH with large numbers of services enabled, the QoS service
  # may take a long time to return a healthy reponse. Therefor, it is expected
  # that the readinessProbe may take a large number of attempts to succeed.
  readinessProbe:
    failureThreshold: 600 # Set to high value to account for the potential long response time of the QoS service.
    httpGet:
      path: /healthz
      port: 3000
      scheme: HTTP
  livenessProbe:
    failureThreshold: 600 # Set to high value to account for the potential long response time of the QoS service.
    httpGet:
      path: /healthz
      port: 3000
      scheme: HTTP

  delve:
    enabled: false
