name: Publish image to GitHub Container Registry

on:
  push:
    ## TODO: Switch back to main once tested
    branches: ["feat/path_docker_images"]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: |
            ghcr.io/buildwithgrove/path
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag,suffix=-rc
            type=sha,suffix=-rc
            type=sha,format=long,suffix=-rc

      ## TODO: Is the GH token in place in the repo?
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ## TODO: Do we want/need to make PATH multi arch?
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .

## TODO: Do we want/need to publish a release?
