name: Build image and push to ghcr.io

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Path tests"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch: # Added to enable manual trigger via GitHub UI

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: |
            ghcr.io/buildwithgrove/path
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag,suffix=-rc
            type=sha,format=short,suffix=-rc
            type=ref,event=branch,pattern=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            IMAGE_TAG=${{ steps.meta.outputs.version }}
            TARGETOS=linux
            TARGETARCH=amd64
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          provenance: false
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Path API
