name: Tag and Release

on:
  push:
    branches: ["main"]

jobs:
  release-on-push:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          release_body: ":rocket: Release Notes !:fireworks: "
          use_github_release_notes: true