name: Path tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linter:
    name: Run golangci-lint
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: Setup Git Authentication
        run: |
          git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 10m --verbose

  unit-testing:
    name: Run unit tests
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: Setup Git Authentication
        run: |
          git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run unit tests
        run: CGO_ENABLED=0 go test ./... -short

  test-docker-build:
    name: Test build of Docker image
    runs-on: "ubuntu-22.04"
    steps:
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            IMAGE_TAG=test
            GITHUB_TOKEN=${{ github.token }}
          push: false
          load: true
          tags: test-build

  e2e-testing:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: copy Shannon E2E config
        run: make copy_shannon_e2e_config

      - name: update Shannon E2E config from secrets
        env:
          SHANNON_GATEWAY_PRIVATE_KEY: ${{ secrets.SHANNON_GATEWAY_PRIVATE_KEY }}
          SHANNON_OWNED_APPS_PRIVATE_KEYS: ${{ secrets.SHANNON_OWNED_APPS_PRIVATE_KEYS}}
        run: ./e2e/scripts/update_shannon_config_from_secrets.sh

      - name: copy Morse E2E config
        run: make copy_morse_e2e_config

      - name: update Morse E2E config from secrets
        env:
          MORSE_GATEWAY_SIGNING_KEY: ${{ secrets.MORSE_GATEWAY_SIGNING_KEY }}
          MORSE_FULLNODE_URL: ${{ secrets.MORSE_FULLNODE_URL }}
          MORSE_AATS: ${{ secrets.MORSE_AATS }}
        run: ./e2e/scripts/update_morse_config_from_secrets.sh

      - name: Run Shannon E2E Tests
        run: make test_e2e_shannon_relay

      - name: Run Morse E2E Tests
        run: make test_e2e_morse_relay
