name: Path tests

on:
  push:
    # TODO_IN_THIS_PR(@commoddity): remove this
    branches: [main, evm-load-test]
  pull_request:
    branches: [main]

jobs:
  run-linter-golangci-lint:
    name: Run linter - golangci-lint
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: Setup Git Authentication
        run: |
          git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 10m --verbose

  run-tests-docker-build:
    name: Run tests - Docker image build
    runs-on: "ubuntu-22.04"
    steps:
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            IMAGE_TAG=test
            GITHUB_TOKEN=${{ github.token }}
          push: false
          load: true
          tags: test-build

  run-tests-unit:
    name: Run tests - Unit
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: Setup Git Authentication
        run: |
          git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run unit tests
        run: CGO_ENABLED=0 go test ./... -short

  run-tests-e2e-morse:
    name: Run tests - Morse E2E
    runs-on: "ubuntu-22.04"
    needs:
      - run-linter-golangci-lint
      - run-tests-docker-build
      - run-tests-unit
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: copy Morse E2E config
        run: make prepare_morse_e2e_config

      - name: update Morse E2E config from secrets
        env:
          MORSE_GATEWAY_SIGNING_KEY: ${{ secrets.MORSE_GATEWAY_SIGNING_KEY }}
          MORSE_FULLNODE_URL: ${{ secrets.MORSE_FULLNODE_URL }}
          MORSE_AATS: ${{ secrets.MORSE_AATS }}
        run: ./e2e/scripts/update_morse_config_from_secrets.sh

      - name: Run Morse E2E Tests
        run: make test_e2e_evm_morse

  run-tests-e2e-shannon:
    name: Run tests - Shannon E2E
    runs-on: "ubuntu-22.04"
    needs:
      - run-linter-golangci-lint
      - run-tests-docker-build
      - run-tests-unit
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: copy Shannon E2E config
        run: make prepare_shannon_e2e_config

      - name: update Shannon E2E config from secrets
        env:
          SHANNON_GATEWAY_PRIVATE_KEY: ${{ secrets.SHANNON_GATEWAY_PRIVATE_KEY }}
          SHANNON_OWNED_APPS_PRIVATE_KEYS: ${{ secrets.SHANNON_OWNED_APPS_PRIVATE_KEYS}}
        run: ./e2e/scripts/update_shannon_config_from_secrets.sh

      - name: Run Shannon E2E Tests
        run: make test_e2e_evm_shannon

