name: Run tests, build image and push to GitHub Container Registry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.22.3"
  LINUX_VERSION: "ubuntu-22.04"

jobs:
  linter:
    name: Run golangci-lint
    runs-on: $LINUX_VERSION
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION

      - name: Setup Git Authentication
        run: |
          git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config=.golangci.yml --timeout 10m --verbose

  unit-testing:
    name: Run unit tests
    runs-on: $LINUX_VERSION
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION

      - name: Setup Git Authentication
        run: |
          git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run unit tests
        run: CGO_ENABLED=0 go test ./... -short

  test-docker-build:
    name: Test build of Docker image
    runs-on: $LINUX_VERSION
    steps:
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            IMAGE_TAG=test
            GITHUB_TOKEN=${{ github.token }}
          push: false
          load: true
          tags: test-build

  e2e-testing:
    runs-on: $LINUX_VERSION
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION

      - name: copy E2E config
        run: make copy_test_config

      - name: update E2E config from secrets
        env:
          GATEWAY_PRIVATE_KEY: ${{ secrets.GATEWAY_PRIVATE_KEY }}
        run: ./e2e/scripts/update_config_from_secrets.sh

      - name: Run E2E Tests
        run: make test_e2e_shannon_relay

  build-and-push:
    needs: 
      - linter
      - unit-testing
      - e2e-testing
    runs-on: $LINUX_VERSION
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: |
            ghcr.io/buildwithgrove/path
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag,suffix=-rc
            type=sha,suffix=-rc
            type=sha,format=long,suffix=-rc

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
